### ISSUE TITLE
RSD adoption by external parties

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/research-software-directory#111]
We want to make the RSD available for use by external parties. We have to keep in mind several things.

# 1. Ease of use vs. easy to extend:
How is the technical skill of the person implementing an RSD clone? Should we provide an easy interface to run a direct clone or make it easier to extend (but harder to get started perhaps)?

# 2. Mono repo / submodules
A mono repo will be easy to extend, e.g. a user will just fork the main repository and continue to work from there in a single repository. This means they don't have to setup multiple Github repositories etc. However, if we update common parts of the code, and we want all instances of the RSD to benefit from this, the code has to be merged, leading to conflicts.

If we split out submodules, a user has to fork each module that they want to customize individually (in Github, and update upstream configuration in local Git folders etc.).

# 3. Generic / specific code
Generic:
- Backend (but plug in schemas)
- Auth
- Admin interface (but plug in settings.json)
- Tasks (but not NLeSC tasks, e.g. projects). Pluggable tasks?

# 4. Base configuration / NLeSC configuration
We can provide a base configuration + NLeSC configuration, or just NLeSC. Just NLeSC configuration means we only have to maintain a single configuration, but we will have to tell users who fork it to strip away the NLeSC parts. On the other hand, if we provide a clean base configuration we will have to maintain this as well for any changes that we make in the future.

# 5. Build & deploy
1. Build on server
- Requires large server with resources that are unused most of the time.
2. Building of Docker images done by developer, push images to server.
- Require docker registry to run on server, more complex configuration.

# 6. Typical questions for extensions / customization:
- I want to customize the schema, how do I do this?
- I want to add a task, where do I add this?
- ...

**Comment by Tommos0** [comment]
We should probably involve stakeholders / potential users in a discussion of how to move things forward.

**Comment by jspaaks** [comment]
Re 2 (mono repo/submodules):

This is something that I'd like to have anyway for making releases. The current ``/landing-page`` setup uses the submodules approach (we haven't updated it in a while though).

With this setup, it becomes really easy for a new user to:

1. follow a doi like https://doi.org/10.5281/zenodo.1154130
1. look at the instructions (that we still have to attach, currently it says something like "_Just testing the release infrastructure. Nothing to see here._")
1. the instructions will say something like 
    
    ```
    cd stack
    docker-compose --file docker-compose-local.yml up --build
    ```
1. and voila, now there is something to interact with.

This, in my opinion, is crucial for adoption: users need to be able to see that it's worth their time **right at the start**.

There is however one caveat regarding the GitHub-Zenodo integration: Zenodo stores only the top level directories, but not their content (see e.g. https://github.com/zenodo/zenodo/issues/1036).

Further note that the monolithic repository / submodules repository can exist alongside the list of separate repositories: it doesn't have to be a replacement as such.

**Comment by jspaaks** [comment]
Re 5 (build on server / build locally, the push to server):

I think the difference between the two options comes down to a few euros per month. Provided that this is indeed the case, I'm perfectly fine with having a server operate at 30% (or something) of its capacity most of the time. You have to keep in mind that the developer who needs to figure out the more complicated setup for the 'push to server' option is not free either, so the 'build on the server' option may not only be technically simpler but also more cost effective.

**Comment by jspaaks** [comment]
Re 1 (easy to get started / easy to extend):

Absolutely, 100%, easy to get started, even if that means it will be more difficult to extend.
