### ISSUE TITLE
Describe software in RSD using rich metadata

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/research-software-directory#112]
http://theswo.sourceforge.net/

**Comment by jspaaks** [comment]
Hi Arnold, 
thanks for the suggestion. We currently already use [CodeMeta](https://codemeta.github.io/) to describe our tools (not fully implemented yet but almost there). The LD-JSON snippets (that we generate from [CITATION.cff](https://citation-file-format.github.io/) files using [``cffconvert``](https://pypi.org/project/cffconvert/) BTW) are currently part of the RSD website, where the information can be picked up by search engine crawlers. Are you suggesting that we should replace the CodeMeta stuff with SoftwareOntology stuff? Or have one next to the other? According to [this table]( https://github.com/codemeta/codemeta/blob/master/crosswalk.csv) I found at the CodeMeta repo, there are many formats to choose from besides Software Ontology. Not sure if we should pick the best (whatever that means) or do all.
Let me know what you think.

**Comment by arnikz** [comment]
@jspaaks: using RDFa in web pages or JSON-LD together with [schema.org](https://schema.org/) is quite relevant for making e.g. software in RSD findable etc. In fact, this controlled vocabulary/ontology has been developed or embraced by Google, Microsoft, Yahoo and Yandex. According to the aforementioned [table](https://github.com/codemeta/codemeta/blob/master/crosswalk.csv) the CodeMeta mirrors and/or extend [schema.org](https://schema.org/) but I'm note quite sure why CodeMeta is needed or why it hasn't embraced existing vocabs/ontologies (incl. SWO, [DOAP](https://github.com/ewilderj/doap) and/or [DCMI](http://www.dublincore.org/documents/dcmi-terms/)). Maybe we should rename this issue to something like "describe software in RSD using rich metadata". to discuss this in general.

**Comment by jspaaks** [comment]
On reasons for CodeMeta over one of the standards you mention: not sure why one is better than another, but from the table it seems they are not exactly the same, therefore it stands to reasons that for specific cases one could be better than an other. Maybe none of it really matters, as long long as you have some rich metadata. 
BTW I'm in favor of changing the name of this issue to "describe software in RSD using rich metadata" like you suggested but then we should close it as well since we are doing that already.

**Comment by arnikz** [comment]
Well, I would argue that it does matter. CodeMeta is pretty new on scene (2017) while other metadata standards such "The" Dublin Core terms/DCMI have been there for many many years to facilitate interoperability in particular. Moreover, digital library systems or archives (incl. Zenodo) heavily rely on the latter standard:)

**Comment by arnikz** [comment]
I'm also not talking about machine reasoning here. I'm suggesting to use community metadata standards (mentioned above) in addition to schema.org vocab. AFAIK Google and others index merely schema.org terms but not derivatives.

**Comment by jspaaks** [comment]
If Google and others ignore anything that's not schema.org, what is the value of adding Dublin Core, or in fact, any of the 20 or so 'standards'? Remember, the sole purpose of adding rich metadata to the site is to be findable through Google.

**Comment by arnikz** [comment]
Indeed, if the sole purpose is the F* through Google/Yandex/Microsoft then you're just fine with (no so rich) schema.org. However, the web is not only about these big companies. I think, one should embrace W3C community standards (a.o. for interoperability etc.). Since RSD has been developed as a digital catalog for software, there has been quite some catalog-related infrastructure developed since 90's and used every day (probably you've searched for peer-reviewed articles etc.) For some historical record, I would recommend to read upon the OAI-PMH protocol or it's successor OAI-ORE (both use DC terms).

**Comment by LourensVeen** [comment]
Looking at the OAI-ORE website, the only listed OAI-PMH providers are academic libraries. Did our survey show that people use library search engines to search for scientific software? If so, then this could be a worthy investment of time.

Looking at bio.tools is interesting. The categories listed are very broad, so if you're looking for a specific solution to a specific problem, then the descriptions are going to be much more useful, and Google will find those just fine. So this thing is more like a review paper. It's good if you want to get an overview of for which problems we have software readily available. That could match with the RSD as the NLeSC portfolio site, but I'm not sure why that should be machine-readable.

**Comment by arnikz** [comment]
@LourensVeen: on contrary, the categories (metadata) listed in bio.tools are as specific as you can get and also incl. input/output formats etc. (note: it's using the EDAM ontology). However, the (correct) "tagging" with terms depends very much on software maintainer. In fact, Google won't help you and/or a software agent/client to find (unambiguously) software that does X and requires files in input format Y and Z, for example, for that you need standardized machine-readable descriptors.

**Comment by jspaaks** [comment]
fixed, codemeta/schema.org metadata is now part of the frontend. Extension beyond what we have now is not foreseen for the near future.
