### ISSUE TITLE
Unable to use () in short statement

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#115]
Software name that are abbreviations are written in a long format in the short statement. For example

`The Astrophysical Multipurpose Software Environment (AMUSE) combines existing numerical codes in an easy to use Python framework. With AMUSE you can simulate objects such as star clusters, proto-planetary disks and galaxies.`

The `()` chars are not allowed in https://github.com/research-software-directory/backend/blob/fb586b3bde46f3b067f6bdbb98c54d65cc9b88b3/schemas/software.json#L526.

Should we allow these chars?

**Comment by jspaaks** [comment]
same for 

1. ``'``
1. ``/``
1. ``+``
1. ``?``

I think having ``(`` and ``)`` in your ``shortStatement`` is testament that your text could be better so I am opposed to include them in the regexp.
