### ISSUE TITLE
Error getting /api: UnauthorizedException: No "Authorization" header in request

### ISSUE THREAD

**Issue by egpbos** [research-software-directory/research-software-directory#117]
<img width="401" alt="schermafbeelding 2018-06-01 om 14 37 55" src="https://user-images.githubusercontent.com/6146598/40841084-81a302bc-65a9-11e8-934c-26806473452e.png">

Before this, I got an OAuth request via Github, which I accepted. Then I was redirected here and now it just shows this, reloading doesn't help.

**Comment by Tommos0** [comment]
Which browser are you using?

**Comment by egpbos** [comment]
Safari

**Comment by egpbos** [comment]
It does work in Firefox.

**Comment by jspaaks** [comment]
I have no experience with it myself but isn't Safari notorious for being well out of date regarding both features and security?

**Comment by egpbos** [comment]
I've never had security issues, but "featureless" (also sometimes referred to as "clean", "simple", "user friendly"...) is indeed a well known Apple feature ;) But not sure whether feature-free is in any case relevant, as it seems more of an engine-problem to me. Safari and Chrome used to be based on the same engine, Webkit, though Google has since forked from that. But should still be pretty similar at the core...

**Comment by Tommos0** [comment]
I have no Mac so it is hard for me to debug this. Do you perhaps see any errors in the Javascript console?

**Comment by egpbos** [comment]
I don't really have time to debug now. I'd be fine with just using Firefox on Mac.

**Comment by egpbos** [comment]
That said, if anyone else wants to debug, I will be grateful ;)
