### ISSUE TITLE
admin interface: help distinguishing between mentions with the same title

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#118]
for example, we could construct the dropdown list item strings by prepending the mention title with the date.

**Comment by Tommos0** [comment]
Template can be changed here: https://github.com/research-software-directory/admin/blob/master/public/settings.json#L200

However, if we add date it will be formatted as ISO8601 (`2018-06-05T17:59:00Z` or something)

**Comment by jspaaks** [comment]
for reference later: https://github.com/research-software-directory/admin/blob/d81e5d8d602aedc72768c922362a7e3f9838b39f/public/settings.json#L200

**Comment by jspaaks** [comment]
@vincentvanhees suggested that we should add a mechanism to ensure that the mentions list only has unique entries i.e. without duplication. (Not sure if that's already the case right now, needs checking).

**Comment by sverhoeven** [comment]
Looking at the *metdata.json files at https://github.com/research-software-directory/db-dump there are no unique indices, so the database does not block duplicates.

A paper, oral presentation, slides and video recording all could have the same title. So we should allow this.

**Comment by vincentvanhees** [comment]
My suggestion did not concern double titles but about double entries. I have 60+ papers linked to my software and it is difficult for me to oversee which entries I added before. How about a check for double doi's? Further, it may help if the admin interface to add mentions would allow for searching by doi rather than title, and if mentions in the RSD could be ordered by date of publication at the moment they seem in random order.

**Comment by jspaaks** [comment]
OK, I think
 "_Further, it may help if the admin interface to add mentions would allow for searching by doi rather than title, and if mentions in the RSD could be ordered by date of publication at the moment they seem in random order._"

should be part of this issue.

---
As for the other part, "double entries": the mentions are scraped from zotero every night. Each mention in de RSD is identified by a unique key. We use the same key value that Zotero uses (i.e. an equal key, not an identical one). If you have double entries, it should be because you entered the data for a given mention multiple times in Zotero. You can check this via Zotero's interface. Each library in Zotero has a ``duplicate items`` folder, and if you happen to have duplicate items, it offers functionality to merge them. 

On the RSD side, you can check which key values are associated with a mention via the api. Not ideal but the best we can do right now. For example: https://www.research-software.nl/api/software_cache/ggir has ``related.mentions[0].foreignKey.zoteroKey = 5Y4XZEWA``.

**Comment by jspaaks** [comment]
- added a date to how the mentions are displayed
- added checks to the schema to ensure that array items are not accidentally duplicates of other array items
