### ISSUE TITLE
one list of env vars

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#119]
We currently have lists of environmental variables divided over multiple repos, with some overlap between lists. It's quite difficult to keep them consistent, e.g.

- ``BACKEND_URL``:
    - https://github.com/research-software-directory/tasks-nlesc/blob/3418bdf6bda32ac65c2da2be30b95cb5e2297dd7/.env.example#L4 
    - https://github.com/research-software-directory/frontend/blob/72657b4aab05d36b613060cecbab9286761b189e/.env.example#L1
    - https://github.com/research-software-directory/stack/blob/bab7519bcc02a652607b49d2d519cc136fcea8dc/.env.example-localhost#L5
- ``AUTH_CALLBACK_URL``:
    - https://github.com/research-software-directory/stack/blob/bab7519bcc02a652607b49d2d519cc136fcea8dc/.env.example-localhost#L1
   - https://github.com/research-software-directory/auth-github/blob/587d66f5a434a581e68213ca779e05849e8763fd/.env.example#L5

It would be better to have one file with a list of all variables in one place (probably ``stack`` repo), and symlink to that one file.

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/stack/blob/master/.env.example-localhost

(might not be up to date)

**Comment by jspaaks** [comment]
Here's list of which variables are used by which repo. I plan to describe them in a table in ``stack`` repo, including a description of how one may acquire the corresponding values. Then, in each repo that uses env vars, name the ones you use and point to the master table in ``stack``. 

- frontend:

    ```
    BACKEND_URL
    ```

- auth-github:

    ```
    JWT_SECRET
    AUTH_GITHUB_CLIENT_ID
    AUTH_GITHUB_CLIENT_SECRET
    AUTH_GITHUB_ORGANIZATION
    AUTH_CALLBACK_URL
    AUTH_ROOT
    ```
- tasks-nlesc:

    ```
    ZOTERO_API_KEY
    ZOTERO_LIBRARY
    GITHUB_ACCESS_TOKEN
    BACKEND_URL
    JWT_SECRET
    DATABASE_PORT
    DATABASE_NAME
    ```
- backend:

    ```
    JWT_SECRET
    DATABASE_HOST
    DATABASE_PORT
    DATABASE_NAME
    SCHEMAS_PATH
    FLASK_DEBUG
    BACKEND_ROOT
    ```

**Comment by Tommos0** [comment]
Stack repo has been merged into this repo (`rsd`/`rsd`).

Root contains an `.env.example`; for running locally (through `docker-compose` or through `tmux-start`, it will expect a `.env` file in the root.

NLeSC specific env is in `ansible/.env.prd` (`git-crypt`'ed).
