### ISSUE TITLE
Error error: TypeError: Cannot read property 'token' of null

### ISSUE THREAD

**Issue by vincentvanhees** [research-software-directory/research-software-directory#122]
I get this error when I try to enter https://www.research-software.nl/admin 
I am using Chrome on Windows.
![rsd](https://user-images.githubusercontent.com/8362333/41316146-dd1851a6-6e91-11e8-8733-dbed459ea07a.png)

**Comment by sverhoeven** [comment]
If I remove the `jwt` token from the local storage with the DevTools, I also see the message for a moment, but then a redirect will clear the error and show the admin page.

Does the page only show the error or does it also show the admin page (black side bar with software/person/mention/project/organization)?

**Comment by vincentvanhees** [comment]
It does not show the admin page or the sidebar. It is just a black screen with 'loading' in the middle:
![rsd](https://user-images.githubusercontent.com/8362333/41348934-87664e52-6f0e-11e8-9dae-08cc4612379e.png)

**Comment by vincentvanhees** [comment]
I left it 'loading' for 12+ minutes and nothing changes. I will be at the center tomorrow, maybe it is easier to look at this with you or someone else from the RSD team in person.

**Comment by vincentvanhees** [comment]
Same problem when I try it in Firefox under Ubuntu, but error message is different:
![screenshot from 2018-06-14 09-35-31](https://user-images.githubusercontent.com/8362333/41398098-7f4434b6-6fb6-11e8-87ed-b6c78e74fe69.png)

**Comment by Tommos0** [comment]
Should be fixed by https://github.com/research-software-directory/admin/commit/6856e70204eac7e0bb5b63cd0c391b13917966d9
@vincentvanhees - Can you confirm?

**Comment by vincentvanhees** [comment]
Thanks, it is fixed now.
