### ISSUE TITLE
Jupyter showcases

### ISSUE THREAD

**Issue by prinsherbert** [research-software-directory/research-software-directory#132]
To determine usefulness, in particular programmers like to see, not just read. Therefore the admin page should allow publishers to select jupyter notebooks and specific cells, inputs or outputs to illustrate the use on the main page.

Ideally the show case can also be run, for example in the browser using webassembly, see issue #135  .

**Comment by jspaaks** [comment]
I think the way to do this is add the appropriate link to the ``Get started`` button, e.g. let it point to a MyBinder or https://codeocean.com/
