### ISSUE TITLE
DOMAIN=localhost does not work when Docker is not running on localhost

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#134]
For example for OSX and Windows the Docker server is running in a virtual machine.

Explain the domain var in .env file.

**Comment by jspaaks** [comment]
It is not possible for us to support setups that are too far from either (1) what we ourselves run; or (2) typical setups that you find on servers. I've added a disclaimer to that effect in the README.

We should still add/improve the descriptions of the environment variables, but that is covered by #196. Closing this one.
