### ISSUE TITLE
Jupyter Notebook integration: run in browser?

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/research-software-directory#135]
It would be very nice, as a showcase, or to reproduce results if we could somehow integrate (Jupyter) notebooks in the RSD.

Possibilities:
- Show in/output screenshots and link to notebook

The problem with Jupyter notebooks is that they need a backend to run, so you can not simply link to a runnable example. It would be nice to have something run completely in browser.

**Comment by jspaaks** [comment]
Wouldn't it be easier if we delegate that sort of thing to e.g. https://codeocean.com, https://mybinder.org, or https://renkulab.io and use the ``Get started`` button to direct a visitor there?
