### ISSUE TITLE
mongo db volume causes mongo crash on OSX

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#136]
The mongo server is crashing with errors about it's data root.

Commenting out `- ./db:/data/db` in docker-compose.yml will start everything correctly, but persistence of db is lost.

**Comment by sverhoeven** [comment]
Instead of using a bind mount use a Docker volume to persist Mongo data.

**Comment by jspaaks** [comment]
The Research Software Directory is intended to run in a Linux environment, for example on AWS. I realize local development is inconvenient for people who use OSX or Windows , but we simply don't have the people to support other platforms than what we ourselves are running.
