### ISSUE TITLE
SEO duplicate text detection

### ISSUE THREAD

**Issue by prinsherbert** [research-software-directory/research-software-directory#138]
Inform publishers when they copied text from git(hub) into the rsd that this damages search engine (Google) ranking.

**Comment by jspaaks** [comment]
I don;t know much about SEO, but I think I know that duplicate information is frowned upon. However, I'm not sure how big a problem this really is. Do you know of a way how we may get insight in this?

**Comment by jspaaks** [comment]
Might not be a big problem since the contents of READMEs don;t seem to be indexed.
