### ISSUE TITLE
Going to a software item that not exists should give 404 but redirects to home

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#140]

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/frontend/blob/master/app/application.py#L136-L138

**Comment by jspaaks** [comment]
maybe something like https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04
or change this https://github.com/research-software-directory/research-software-directory/blob/ee8c89f49373280cf3d0ceca09898f7154bfa92a/frontend/app/application.py#L166-L168

**Comment by cwmeijer** [comment]
The same problem for path /projects/xyz. This path should give the same 404 page, maybe with some pointers to various parts of the site.

**Comment by eriktks** [comment]
Fixed by PR #592
