### ISSUE TITLE
Software does not show up if contributor does not have an affiliation

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/research-software-directory#142]
When adding software with 3 contributors without an affiliation, the admin interface does not complain, but the software does not show up in the frontend. When visiting the software page directly on https://localhost/software/smartsockets the docker prints and error:

``
backend_1   | 172.30.0.6 - - [12/Jul/2018:14:26:03 +0000] "GET /api/software_cache/smartsockets HTTP/1.1" 200 110675 "-" "python-requests/2.19.1"
frontend_1  | [2018-07-12 14:26:03,226] ERROR in app: Exception on /software/smartsockets [GET]
frontend_1  | Traceback (most recent call last):
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
frontend_1  |     response = self.full_dispatch_request()
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
frontend_1  |     rv = self.handle_user_exception(e)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
frontend_1  |     reraise(exc_type, exc_value, tb)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
frontend_1  |     raise value
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
frontend_1  |     rv = self.dispatch_request()
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
frontend_1  |     return self.view_functions[rule.endpoint](**req.view_args)
frontend_1  |   File "/src/app/application.py", line 106, in software_product_page_template
frontend_1  |     mention_types=mention_types,
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
frontend_1  |     context, ctx.app)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
frontend_1  |     rv = template.render(context)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
frontend_1  |     return original_render(self, *args, **kwargs)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
nginx_1     | 172.30.0.1 - - [12/Jul/2018:14:26:03 +0000] "GET /software/smartsockets HTTP/1.1" 500 291 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
frontend_1  |     return self.environment.handle_exception(exc_info, True)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
frontend_1  |     reraise(exc_type, exc_value, tb)
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
frontend_1  |     raise value.with_traceback(tb)
frontend_1  |   File "/src/app/../templates/software/software_template.html", line 1, in top-level template code
frontend_1  |     {% extends "layout_template.html" %}
frontend_1  |   File "/src/app/../templates/layout_template.html", line 65, in top-level template code
frontend_1  |     {%- block content -%}{%- endblock -%}
frontend_1  |   File "/src/app/../templates/software/software_template.html", line 33, in block "content"
frontend_1  |     {% include 'software/contributors.html' %}
frontend_1  |   File "/src/app/../templates/software/contributors.html", line 60, in top-level template code
frontend_1  |     {{contactPerson.affiliations[0].foreignKey.name}}
frontend_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
frontend_1  |     return getattr(obj, attribute)
frontend_1  | jinja2.exceptions.UndefinedError: list object has no element 0
frontend_1  | 172.30.0.7 - - [12/Jul/2018:14:26:03 +0000] "GET /software/smartsockets HTTP/1.0" 500 291 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
``

**Comment by jmaassen** [comment]
And the frontend prints:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jspaaks** [comment]
It looks like this was another instance of #157, which was actually due to the ``contactPerson`` not having an affiliation.
