### ISSUE TITLE
Explain how/where to add software/person/... entries

### ISSUE THREAD

**Issue by bencomp** [research-software-directory/research-software-directory#143]
Now that I have a local RSD running with automatically loaded NLeSC data, I would like to know how to add new information about my own stuff.

The [README for tasks-nlesc](https://github.com/research-software-directory/tasks-nlesc/blob/master/README.md) already explains to some extent what various tasks do, but there is no overview of what information I should add where.

New software packages can only be add via the admin interface, apparently. And people must be added in the admin too; they are not read from CITATION.cff files or Zenodo releases.

Please add an overview of information sources and flow.

**Comment by jspaaks** [comment]
should be fixed by https://github.com/research-software-directory/instruction/pull/70
