### ISSUE TITLE
Date recognition when month and day number are swapped?

### ISSUE THREAD

**Issue by vincentvanhees** [research-software-directory/research-software-directory#151]
@arnikz pointed out to me that I have publications in Zotero for whom the date is incorrectly recognized by the RSD and that the month and day are mixed up, e.g. 12-4-2018 is recognized as 12 December. I auto-retrieved the meta-data via a doi search in Zotero, so the source of the problem is in inconsistent date formats in the doi sources itself. I think it is not ideal that I now have to manually start checking all publication metadata for correctness. From my perspective, the best solution would be if the RSD could check for incorrect date entries and fix them automatically. Is this possible?

**Comment by vincentvanhees** [comment]
Sorry, so far I relied on the info @arnikz gave me without looking it up myself. I have now looked into it and think the problem is more serious than a simple month/day swap.

I looked doi: 10.1186/s12966-018-0664-6, 10.1186/s12889-018-5215-1 and 10.1038/s41598-018-26279-7. If I extract the meta-data for these dois in Mendeley it says that these articles were all published on the date as specified on the journal page, but with the month of publication replaced by December 2018. So, it would seem that this is not a formatting error.

Possible explanations:
- The articles are scheduled for publication in paper format in December, while the digital open access version was published earlier this year.
- Human mistake.
- This is a trick by journals to fake higher impact factors, because the official publication date is later and therefore the number of citations will be higher within the 2 year window after 'publication'. I have 8 zotero entries from December 2017, supporting this theory.

If the last explanation is truly the problem then that would help to narrow down the issue to all publications in December of any year. However, I doubt that there is an easy fix to it.

@arnold shall we just ignore all this, but keep in mind that publication dates can be skewed to December? To me it doesn't sound like a major problem for the RSD, it is more a problem for the integrity of journal impact factors.

@ jspaaks a quick pragmatic solution could be to replace all future publication dates automatically with the present date.

**Comment by jspaaks** [comment]
If I use Zotero's _Add by identifier_ functionality to add ``10.1186/s12966-018-0664-6``, the ``Date`` field in the resulting record says ``12/2018``: so looks like a problem with metadata if anything. Note that you could edit those dates by hand if you wanted to (but at the cost of no longer being consistent with the metadata attached to the original DOI). Either way, I don;t think it's a big problem for the Research Software Directory, especially once my PR https://github.com/research-software-directory/frontend/pull/86 gets merged.

**Comment by vincentvanhees** [comment]
Ok, sounds like a good solution.
The information that Mendely has which Zotero does not have is: page number and full publication date: 25th of December 2018. Maybe it is because Mendeley also collects information from its users.
