### ISSUE TITLE
Unable to log in to admin interface

### ISSUE THREAD

**Issue by bouweandela** [research-software-directory/research-software-directory#154]
When I try to log in to the admin interface, I first see this screen:
![screenshot from 2018-09-07 09-20-11](https://user-images.githubusercontent.com/5430937/45204794-96c74580-b280-11e8-9536-a413eac7982a.png)
and then this one:
![screenshot from 2018-09-07 09-29-01](https://user-images.githubusercontent.com/5430937/45204804-9f1f8080-b280-11e8-84ad-5e8cd3608576.png)
Clicking the button again just repeats the two screens above.

**Comment by Tommos0** [comment]
Should be fixed, there were some proxy configuration issues
