### ISSUE TITLE
Activity plot flatlines despite nonzero commit data for 2 months

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#155]
https://www.research-software.nl/api/software_cache/cffinit
says

```json
"commits": {
	"2018-08": 88,
	"2018-09": 2
},
```

but activity plot is empty / flatlines.

**Comment by Tommos0** [comment]
Two things:
- off by one error (because JS starts counting months at 0 (for January))
- doesn't show last month

So you don't get the current or the last month

**Comment by Tommos0** [comment]
fixed https://www.research-software.nl/software/cffinit
