### ISSUE TITLE
requests for statistics

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#156]
This issue is meant to create a record of what statistics people would want to be able to extract from the Research Software Directory.

**Comment by jiskattema** [comment]
Next to the RSD, we use Zotero for dataentry, and to keep track of a larger set of output than is listed in the RSD. The items below are for what should be in Zotero.

For the self-assessment report
==

* count of peer reviewed journal papers and 'serious' conference papers (co)authored by the eScience Center on *escience*, per year
* count of peer reviewed journal papers and 'serious' conference papers (co)authored by the eScience Center in a specific *domain*, per year
* count of peer reviewed journal papers and 'serious' conference papers funded by the eScience Center, per year

The quality and intensity of peer review for conference papers varies per domain. For instance, in computer science some conferences are much more prestigious than journals. For other fields, conference papers almost don't count. Therefore *serious* as used above is very hard to define, and for now means 'any'.

Other items of interest
==

* count of software releases (with DOI)
* count of dataset releases (with DOI)

As there is no equivalent process to peer review for software or datasets, that is accepted by the scientific community, it is not clear yet what the selection criteria should be here; having a DOI is required but probably not sufficient.

examples of noteworthy:
* appearances in the media: press, television, radio
* presentations, posters, demos
* outreach activities

Do not add to Zotero
==

Please do not add items that are not directly attributable to our funding:
* please do not add your personal references and papers to the eScience group
* please do not add papers build on your work, or use your tools. Although these are useful to have, and show our wider impact, if you add them they show up in the wrong lists.

We should find a workable alternative for these items. Possibly a separate Zotero collection.

**Comment by jspaaks** [comment]
Hey Jisk,
thanks for this write-up, good to have for future reference.
