### ISSUE TITLE
Allow simple adding of projects in admin interface

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/research-software-directory#158]
Currently is it not possible to manually add a project (like you would add an organization or person).

Although this makes sense the eScience Center where we can mine the corporate page for a list of projects, this complicates setting up and RSD for an external organisation, such as the PROCESS and Ibis RSD instances I'm working on now. 

Also within the eScience Center we have software that is (or was) also used in external projects that are not on our corporate project page. Some of the Ibis stuff used in the NFI and DTEC projects are an example of this. 

For adding a project, just providing a name, logo and URL would typically be enough. Very similar to the adding person or adding organization already offered in the admin interface.

**Comment by jspaaks** [comment]
Prototype has been implemented for the PROCESS instance https://github.com/process-project/research-software-directory. We will test and develop the setup there, then push back upstream if necessary. Closing this issue.
