### ISSUE TITLE
Software description page is not clear

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/research-software-directory#173]
The description of software has as the bottom the 'Mentions' section.
Its is not clear what a mention is, a short description, or a help button, (or tooltip?) should be added.
For example:
* are the mentions publications / etc by the authors of the software
* are the mentions publications / etc by others about the software
* are they from users of the software?
* all of the above?

**Comment by jspaaks** [comment]
All of the above. Basically, anything that will help provide context to a software item. For reference, here's some updated documentation https://github.com/research-software-directory/research-software-directory/tree/b3adc4dfa7efc18fb4b7fa7572a2bb304659cc87/docs/instruction
