### ISSUE TITLE
update cffconvert dependency

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#185]
So I tried simply updating the requirements file in ``tasks`` to ``cffconvert==1.0.3`` (the latest version),
but that gave me errors when building the docker container.

The error seemed related to ``ruamel.yaml`` vs. ``PyYAML``. ``cffconvert==1.0.3`` uses ``PyYAML`` as its dependency, but one of the other dependencies (``pykwalifire``) has ``ruamel.yaml`` as a dependency. The RSD uses an earlier version of ``cffconvert`` (0.0.3) which did not use ``pykwalifire``, so it wasn't a problem before.

So now I've updated ``cffconvert`` to use ``ruamel.yaml`` in a version that is within the dependency range of ``pykwalifire``. 
https://github.com/citation-file-format/cff-converter-python/pull/86/files
I was surprised that worked at all.

I haven't made a new release of ``cffconvert`` yet, but in order to check whether this solved the build issues for the docker container, I've changed the requirements.txt in ``tasks`` to
point to the specific git SHA in cff-convert-python. This meant that I had to install git in the ``tasks`` Dockerfile: 

```
RUN apk add --no-cache git
```

When building based on the changed Dockerfile, this yielded another problem, namely that of a missing ``gcc``. Apparently this is needed by ruamel? I don;t know. Anyway I've added ``build-base``:

```
RUN apk add --no-cache git build-base
```

Now it seems to work.

for reference: https://github.com/research-software-directory/tasks-nlesc/compare/b3c2d4fbd49ce5a7011c242da474669f19f3c50c..199b566133fe9019ebb6a4a2fb1f41f1a0771d16

**Comment by Tommos0** [comment]
Yea I think I ran into this same problem when deploying cff-convert as a google cloud function. I think I fixed it in the same way :)
