### ISSUE TITLE
Graphs has api url hardcoded

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#200]
See https://github.com/research-software-directory/research-software-directory/blob/monorepo/graphs/src/App.vue#L36 it should be relative.

**Comment by jspaaks** [comment]
but making it relative ``/api/software_cache`` breaks the development build. Maybe @sverhoeven knows how to fix this?

**Comment by sverhoeven** [comment]
That should be resolvable by adding a proxy (https://cli.vuejs.org/config/#devserver-proxy) to `graphs/vue.config.js`. Calls to `/api` will then be proxied to another web server like the backend server.

**Comment by jspaaks** [comment]
14c27555edbeb7e881f3522c9eb23bcea9b325f0 is what should work.

**Comment by jspaaks** [comment]
I propose to fix this later (i.e. not in release 1.1.0), and we should probably refactor the graphs microservice a bit to make it more Vue-ish and less Angular/React-ish

**Comment by jspaaks** [comment]
Issue was solved https://github.com/research-software-directory/research-software-directory/blob/3760355ed7be6c718a04d35710cbbf41efae80ac/graphs/src/metrics.js#L422
