### ISSUE TITLE
How to avoid out-of-date DOIs on software pages?

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#22]
Xenon is currently at version 2.2.0 but I found that its DOI on https://www.research-software.nl/software/xenon still pointed to version 1.1.0. While that has been corrected now, it's apparently pretty easy for the DOI in the admin interface to not get updated when the software gets a new release. 

I see a couple of ways to deal with this:

First off, there should be a button ``Test`` in the DOI field, that will take you to wherever the DOI is pointing. Having the URL as part of the software page would also help currently it's only the second half of the url plus it's not hyperlinked).

Second, we could instead use the version-agnostic doi that Zenodo provides (Zenodo doesn't advocate that, because you loose the specifics of the software version when you're using it for a paper)

Third, we could remove the DOI field entirely from the admin interface, and use the information from CITATION.cff instead (see also #21, we could ask people to fill in their list of repos that together constitute a 'brand' such as ``Xenon`` or ``Noodles``, and have them assign a label ``citation`` or something to exactly one of them to indicate that "this is where the citation information comes from"). ~~This option is problematic for brands that have no GitHub repos associated with them~~ no wait, we already have the local citationcff fallback which should include a DOI.

**Comment by sverhoeven** [comment]
We now follow the doi to a concept doi. The concept doi is used to download all versions.

**Comment by sverhoeven** [comment]
If a task fails to resolve the doi to releases/versions and a cff file then report it in the status page https://github.com/research-software-directory/landing-page/issues/60
