### ISSUE TITLE
merge stack and landing page repos?

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#23]
Is is a good idea to merge the ``landing_page`` repo into ``stack`` repo? They seem to complement and/or do the same thing. 

(Could be dependent on whether we decide to merge ``stack``'s ``dev`` branch into ``stack``'s master branch.)

**Comment by jspaaks** [comment]
Along similar lines: how about we merge the repos together into one. Reason I ask is that I just had the most difficult time making pull requests to different repos, and in the end, changes in say, the frontend, go hand in hand with changes to the backend or admin interface anyway. IMHO, merging them all into one would result in:

- an easier way to do releases
- an easier way to run the whole stack
- one entrypoint to make issues
- easier branching
- easier merging of pull requests

But perhaps there are downsides too.

**Comment by jspaaks** [comment]
@sverhoeven suggests renaming ``/landing-page`` to ``/research-software-directory`` in order to comply with convention

**Comment by Tommos0** [comment]
has been done
