### ISSUE TITLE
some repos still have deploy keys

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#246]
- https://github.com/research-software-directory/db-dump/settings/keys
- https://github.com/research-software-directory/backend/settings/keys
- https://github.com/research-software-directory/admin/settings/keys
- https://github.com/research-software-directory/auth-github/settings/keys

**Comment by Tommos0** [comment]
one of the `db-dump` is used to store DB backups in Github. The others are used by Dockerhub, and can be removed (with #243 #244 #247).

**Comment by jspaaks** [comment]
this issue now part of #254 , closing
