### ISSUE TITLE
clean up dockerhub presence

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#247]
as far as I'm concerned, we should delete

- https://hub.docker.com/r/rsdnlesc/backend
- https://hub.docker.com/r/rsdnlesc/admin
- https://hub.docker.com/r/rsdnlesc/auth-github
- https://hub.docker.com/r/rsdnlesc/frontend

but leave ``https://hub.docker.com/r/rsdnlesc/docker-term-letsencrypt`` for now, because **that's still used.**

**Comment by jspaaks** [comment]
- https://hub.docker.com/r/rsdnlesc/auth-github
- https://hub.docker.com/r/rsdnlesc/frontend
are stil alive for some reason. reopened for now.

**Comment by Tommos0** [comment]
Weird, cleaned again:
https://cloud.docker.com/u/rsdnlesc/repository/list

Is travis still pushing something maybe?
