### ISSUE TITLE
switch production instance

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#254]
I configured a new instance (ID ``i-090c3e210ebf5e2d8``) on AWS as user ``rsd``, including backup mechanism to AWS S3. We still need to migrate the data from RSD v2 instance ID ``i-0eddd76bd5fa7ed95`` to the new instance.

see:
- EC2 dashboard https://eu-central-1.console.aws.amazon.com/ec2
- S3 dashboard https://s3.console.aws.amazon.com/s3

steps 
1. let research-software.nl point to new instance by updating DNS record
1. migrate data from old instance to new instance
1. delete db-dump deploy key
1. mark db-dump repo as archived

**Comment by Tommos0** [comment]
Instead of updating the DNS record, you could move the IP address to the new instance (if it's a floating IP)
