### ISSUE TITLE
Docker-compose runs into error with nginx_ssl

### ISSUE THREAD

**Issue by geyslein** [research-software-directory/research-software-directory#264]
I tried to set up a test instance following your very detailed and comprehensible guide. However, I am running in the following error message at the end of the composition-process:

`ERROR: for nginx_ssl  Cannot start service nginx_ssl: driver failed programming external connectivity on endpoint rsd-nginx-ssl (a5ea6785ef53a3fcd0bab40309a00796712e44fb975abf3bc2dd98139154e92b):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.19.0.9:443 ! -i br-d5f3e31d7937: iptables v1.8.2 (legacy): unknown option "--dport"
Try ``iptables -h' or 'iptables --help' for more information.
 (exit status 2))
ERROR: Encountered errors while bringing up the project.`

I am not very familiar why --dport is an unknown option here for iptables.

**Comment by jspaaks** [comment]
Hey thanks for the report. What operating system are you running this on? Also, which versions of docker and docker-compose?

**Comment by Tommos0** [comment]
Related: https://github.com/docker/for-linux/issues/481

Updating to a new docker version (or downgrading `iptables`) might work

**Comment by geyslein** [comment]
Hey @Tommos0 your hint helped. thanks a lot, it's running :)
