### ISSUE TITLE
rsd-reverse-proxy: host not found

### ISSUE THREAD

**Issue by geyslein** [research-software-directory/research-software-directory#265]
When running 

`docker-compose --project-name rsd up --build` 

I get the following output from the console: 

`rsd-nginx-ssl    | 172.19.0.1 - - [29/Mar/2019:16:00:39 +0000] "GET / HTTP/1.1" 301 178 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "-"
rsd-nginx-ssl    | 2019/03/29 16:00:39 [error] 16#16: *10 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.19.0.7:80/", host: "localhost"
rsd-nginx-ssl    | 172.19.0.1 - - [29/Mar/2019:16:00:39 +0000] "GET / HTTP/1.1" 502 166 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0" "-"
rsd-nginx-ssl    | 2019/03/29 16:00:44 [error] 16#16: *3 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/software HTTP/1.1", upstream: "http://172.19.0.7:80/api/software", host: "localhost"
rsd-nginx-ssl    | 172.19.0.1 - - [29/Mar/2019:16:00:44 +0000] "GET /api/software HTTP/1.1" 502 166 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0" "-"
rsd-nginx-ssl    | 172.19.0.1 - - [29/Mar/2019:16:00:48 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "-"
rsd-nginx-ssl    | 2019/03/29 16:00:48 [error] 16#16: *15 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.19.0.7:80/", host: "localhost"
rsd-nginx-ssl    | 2019/03/29 16:00:51 [error] 16#16: *15 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.7:80/favicon.ico", host: "localhost", referrer: "https://localhost/"
rsd-nginx-ssl    | 172.19.0.1 - - [29/Mar/2019:16:00:51 +0000] "GET /favicon.ico HTTP/1.1" 502 568 "https://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "-"
rsd-reverse-proxy | 2019/03/29 16:00:57 [emerg] 6#6: host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy | nginx: [emerg] host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy exited with code 1
rsd-reverse-proxy | 2019/03/29 16:02:03 [emerg] 6#6: host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy | nginx: [emerg] host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy exited with code 1
rsd-harvesting   | 2019-03-29 16:02:39,400 releases [INFO] 1/125 "KNIME node for Kripo": 10.5281/zenodo.597262 no valid CITATION.cff found in any release.
rsd-reverse-proxy | 2019/03/29 16:03:09 [emerg] 7#7: host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy | nginx: [emerg] host not found in upstream "auth" in /etc/nginx/conf.d/default.conf:15
rsd-reverse-proxy exited with code 1
`

localhost throws a 502. Am I still missing some configuration? I think I followed the guidelines as you described. Thanks a lot for helping me out.

**Comment by jspaaks** [comment]
One possible explanation would be if you forgot to 
```
source rsd-secrets.env
```
in the terminal where you start
```
docker-compose --project-name rsd up --build
```

**Comment by geyslein** [comment]
Thanks Jurriaan, that was indeed the solution. I didn't get the point that you have to -source- each time before you start the docker-compose - not at all familiar with docker....

**Comment by jspaaks** [comment]
It's an easy mistake to make, it has tripped me up more than a few times. But I'm glad it works now. Thanks for testing out the software, let us know if you experience other problems.
