### ISSUE TITLE
Cannot log in to https://www.research-software.nl/admin/

### ISSUE THREAD

**Issue by vincentvanhees** [research-software-directory/research-software-directory#282]
I was hoping to do a quick update via https://www.research-software.nl/admin/

- The dark grey screen loads briefly
- followed by red box with message "Type error n is null"
- followed by a white page

I tried Chrome, Firefox, and Microsoft Edge.

**Comment by Tommos0** [comment]
Confirmed, having the same problem. @jspaaks , did you change anything?

**Comment by jspaaks** [comment]
Same white screen here. Hard to tell if it's due to changes I made, but I don't think so, since the production site is still running 1.0.0, not 1.1.0.

**Comment by jspaaks** [comment]
btw 1.1.0 seems to work for the moment at least (firefox, https://software.process-project.eu/admin). So maybe we should just update research-software.nl to the newer version instead of figuring out what is going wrong with 1.0.0.

**Comment by Tommos0** [comment]
It could be a difference in the data though.

I noticed the data dump at https://www.research-software.nl/api/ is now more than 18 megabyte, this is not good. It's almost all because of a lot of image data duplication caused by the flattening of the data. Not sure if this is causing this exact problem though, but it might be.

**Comment by sverhoeven** [comment]
Running a local copy of rsd nlesc gives same problem.

Found problem In https://github.com/research-software-directory/research-software-directory/blob/6b56f24224cab553ded7aaf564a045957ed3ea0a/backend/src/routes.py#L261 
If there are more than 1000 resources for a certain type defined then nothing is returned.

There are now 1056 mentions, so the mentions are not returned by the backend anymore.

**Comment by Tommos0** [comment]
> Running a local copy of rsd nlesc gives same problem.
> 
> Found problem In
> 
> https://github.com/research-software-directory/research-software-directory/blob/6b56f24224cab553ded7aaf564a045957ed3ea0a/backend/src/routes.py#L261
> 
> 
> If there are more than 1000 resources for a certain type defined then nothing is returned.
> There are now 1056 mentions, so the mentions are not returned by the backend anymore.

hmm, I think it was necessary for something (I think for leaving out commits because there are bazillions of them). Should have left a comment there :o

**Comment by sverhoeven** [comment]
Yep, by excluding commits and software_cache from  https://www.research-software.nl/api/  endpoint the response is about 4Mb.

**Comment by Tommos0** [comment]
Fixed!
