### ISSUE TITLE
ACMEv1 no longer allowed to make new certificates

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#307]
Looks like there is a new error when creating certificates due to deprecated ACMEv1.

```
rsd-nginx-ssl    | ls: /etc/letsencrypt/live: No such file or directory
rsd-nginx-ssl    | + certbot certonly --webroot -w /acme -n --agree-tos --email rsd@esciencecenter.nl -d localhost --expand
rsd-nginx-ssl    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
rsd-nginx-ssl    | Plugins selected: Authenticator webroot, Installer None
rsd-nginx-ssl    | An unexpected error occurred:
rsd-nginx-ssl    | The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

Line that I think triggers the error: https://github.com/Tommos0/docker-term-letsencrypt/blob/73f531e4c35992b296541f5ab88f042087b69625/certbot.sh#L20

Further reading

- certbot docs https://certbot.eff.org/docs/man/certbot.html?highlight=certonly
- letsencrypt docs about acme client https://letsencrypt.org/docs/client-options/
- alpine linux wiki https://wiki.alpinelinux.org/wiki/Nginx_as_reverse_proxy_with_acme_(letsencrypt)

**Comment by Tommos0** [comment]
I've updated nlesc/docker-term-letsencrypt:latest . Could you try with the new versioN?

**Comment by jspaaks** [comment]
Looks like everything is working again. Thanks Tom!
