### ISSUE TITLE
make order of admin formfields same as how they appear in the website

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#31]
to help see people what information needs to be entered where.

**Comment by sverhoeven** [comment]
The sortIndex in https://github.com/research-software-directory/admin/blob/b3f240771eef85d729dc2ac2c67b9c64163a141f/public/settings.json#L1 specifies in which order the fields are displayed in the admin interface.

**Comment by sverhoeven** [comment]
@jspaaks can you add the sortIndex for all fields.
