### ISSUE TITLE
apache in the way on amazon

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#316]
On Amazon, I (now) get errors when starting the rsd with docker-compose up

The error has something to  do with port 80 being occupied. So maybe add something like this to the documentation:

If you get errors about not being able to start the ``rsd-nginx-ssl`` service:

```sh
ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint proxy (294456d5ddc7a611be9a075d06ff1816924dcb4ddb1f88defe87d7c89a3592ae): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
```

Check what process is occupying port 80 with:

```sh
sudo netstat -tulpn | grep -e 80 -e 443
```

If you see ``apache2``, check that service's status with 

```sh
sudo systemctl status apache2
```

Then stop it

```sh
sudo systemctl stop apache2
```

And disable it:

```sh
sudo systemctl disable apache2
```

Or even more drastic

```sh
sudo apt remove apache2
```

**Comment by Tommos0** [comment]
Apache shouldn't be installed in the first place I think?

**Comment by jspaaks** [comment]
Agree, but that is what I got from Amazon. I even searched by the AMI, such that it would give me the same image as what we are currently using. Weird, no?

**Comment by jspaaks** [comment]
I think the problem comes from the fact that I followed the instructions (Take note, kids).

The link to installing ``git`` says ``sudo apt install git-all`` (whereas I would normally do ``sudo apt install git``)

``git-all`` comes with a bunch of dependencies, among which is ``gitweb``, which itself has a "recommends" dependency on ``apache2`` (I'm basing this off of the properties Tab in Synaptic).

**Comment by jspaaks** [comment]
updated the instructions to install ``git``, not ``git-all``.
