### ISSUE TITLE
logs fill all available disk space

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#330]

**Comment by Tommos0** [comment]
See https://docs.docker.com/compose/compose-file/#logging

Here is an example docker-compose.yml file that limits logging storage:

version: "3.7"
services:
  some-service:
    image: some-service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

The example shown above would store log files until they reach a max-size of 200kB, and then rotate them. The amount of individual log files stored is specified by the max-file value. As logs grow beyond the max limits, older log files are removed to allow storage of new logs.

**Comment by jspaaks** [comment]
Awesome, thanks Tom. I'll see if I can add this shortly.

**Comment by jspaaks** [comment]
After running for 118 hours, here is how the individual services log size are proportioned:

```
7.9M harvesting.log
3.8M nginx_ssl.log
2.7M database.log
1.8M reverse-proxy.log
1.1M backend.log
541K frontend.log
 14K auth.log
 11K backup.log
  24 graphs.log
```

with schedule:
```
0                5    *   *     *       cd /app && python app.py harvest citations && python app.py harvest commits && python app.py harvest metadata
0,10,20,30,40,50 *    *   *     *       cd /app && python app.py harvest mentions
5,15,25,35,45,55 *    *   *     *       cd /app && python app.py resolve
```
