### ISSUE TITLE
replace letsencrypt image with a more featureful, better maintained alternative

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#339]
a nicer alternative to rsdnlesc/docker-term-letsencrypt could be this: https://docs.traefik.io/user-guides/docker-compose/basic-example/ . It works by using labels in the docker-compose file, has a lot more features, and it better maintained :).

_Originally posted by @Tommos0 in https://github.com/research-software-directory/research-software-directory/pull/335_

**Comment by sverhoeven** [comment]
My suggestion would be to use https://hub.docker.com/_/caddy

**Comment by fdiblen** [comment]
@sverhoeven can we close this already?

**Comment by sverhoeven** [comment]
Yep done in #519
