### ISSUE TITLE
update documentation on how to do development on the admin interface without dockerizing

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#349]
I want to debug something in the admin interface, but I can't get to the point where I see the dev build running locally in my browser. Here are the steps I did:

 ```
# Verify there's no old state, e.g.
# - docker volumes
# - docker bind mounts
# - containers
# - images

source rsd-secrets.env

# build all
docker-compose build

# all services up except admin
docker-compose up -d auth backend backup database frontend \
graphs harvesting nginx_ssl reverse-proxy

cd admin

# (using nvm)
# (uninstall "the other" yarn)
# install yarn
npm install -g yarn

# install admin's dependencies
yarn install

# use docker inspect to find out the IP address of 'backend' and 'auth' services
docker inspect rsd-backend | jq '.[]["NetworkSettings"]["Networks"]["rsd_default"]["IPAddress"]'
docker inspect rsd-authentication | jq '.[]["NetworkSettings"]["Networks"]["rsd_default"]["IPAddress"]'

# update package.json "proxy" values, replace localhost by the IP addresses, 
# keep the port numbers

# update package.json "homepage" value to http://localhost/admin

yarn start
```

**Comment by sverhoeven** [comment]
Now the admin has been configured so development on it can be done by running the backend and auth services without Docker as it is using localhost for the proxies. 

We can either 
1. Dont use Docker for our other services when trying to develop one service
2. Do use Docker for our other services when trying to develop one service

If we decide on one we can adjust the docs and config files. We should not have both options documented, that will be I think to confusing.

**Comment by jspaaks** [comment]
Agree on avoiding confusion by offering one option per service, and preferably the same option across services. I think option 2 is preferable, as under that option everything can stay as it would normally be, except for the one service that you want to do interactice development on, without dockerizing it.

One possible problem with option 2 could be that the dockerized services may expect a static volume, e.g. ``rsd_static_admin``, while the non-dockerized service (say, ``admin``) has its own files being hosted. But maybe an ``rsync`` or a symlink can take care of that.

**Comment by Tommos0** [comment]
After discussing with @sverhoeven , we had some ideas, but they might require some more thought.

We could simplify things by combining the Python-based services into a single one (combining auth-github, backend, harvesting, frontend into a 'single' codebase). The main website could also be built from this codebase as a completely static website. Then for development what will be needed is:
- Run mongoDB on localhost (docker/non-docker)
- Run the (combined) backend without Docker,
- Run the admin interface without Docker (and same for Graphs, perhaps).

Production could still use docker-compose, but maybe a single Docker container is then more straight forward?

**Comment by jspaaks** [comment]
PR #537

**Comment by sverhoeven** [comment]
Completed in PR #610 using a extra docker-compose file
