### ISSUE TITLE
software template has irrelevant conditional

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#38]
https://github.com/research-software-directory/frontend/blob/842ca9005e59efd67ed92d50ff5c37438613bc4e/templates/software_template.html#L158

**Comment by jspaaks** [comment]
something like a ``canCite: bool`` property seems a useful alternative.

**Comment by sverhoeven** [comment]
The task that fetches the citation data from Zenodo/GitHub/cff will set this boolean in the software_cache collection..

**Comment by sverhoeven** [comment]
Currently In v2 the conceptDoi is used to determine whether software is citable.

**Comment by jspaaks** [comment]
@sverhoeven: you say _"Currently In v2 the conceptDoi is used to determine whether software is citable."_ but that should not be the case. The ``conceptDOI`` is at the beginning of the pipeline, at that point you do not know whether a software item is in fact citable. Based on the concept doi, the following happens:
- ``get_citation_data`` task (either [this one](https://github.com/research-software-directory/tasks-nlesc/blob/a885f81c71bfb0bfc19fd44eb2cf55a16ce0f0ce/get_citation_data.py), or something like it) resolves the conceptDOI
- verifies that is in fact a concept DOI, not a version DOI
- compiles a list of github releases that existed at the time the Zenodo entry was made based on e.g. https://github.com/research-software-directory/tasks-nlesc/blob/a885f81c71bfb0bfc19fd44eb2cf55a16ce0f0ce/get_citation_data.py
- culls that list by only including releases that currently exist
- and cull THAT list by only including releases that have a CITATION.cff that is valid (while ignoring the ``commit``, ``date-released``, and ``doi`` keys found in the CITATION.cff because of [reasons](https://github.com/research-software-directory/landing-page/issues/77)).


Only at the end of this processing pipeline can you determine whether the conditional (``canCite`` or ``isCitable`` or something) is ``true`` or ``false``.

**Comment by jspaaks** [comment]
issue is being worked on here https://github.com/research-software-directory/tasks-nlesc/commit/c2667c069bc7c3818817c0430ecbc1c1da864402
