### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by c-martinez** [research-software-directory/research-software-directory#397]
I recently discovered that Software Heritage provide a [bibtex citation format](https://ctan.org/pkg/biblatex-software?lang=en) for software.

Would it be an idea for the RSD to provide bibtex citations in this format?

**Comment by jspaaks** [comment]
Hi Carlos,
thanks for the suggestion. Is what you are suggesting different from links such as https://research-software.nl/cite/grlc?version=v1.3.3&format=bibtex ?

**Comment by c-martinez** [comment]
Hi @jspaaks ,

Yes -- it would be an upgrade on current bibtex data produced, extending the `@misc` entries to `@software` entries. Currently bibtex entries are generated in this format:
```bibtex
@misc{YourReferenceHere,
author = { Albert Meroño-Peñuela and Rinke Hoekstra and Carlos Martinez and Richard Zijdeman},                                                                                                                                                                                                    title  = {grlc},
month  = {5},
year   = {2020},
doi    = {10.5281/zenodo.3819202},
url    = {https://github.com/CLARIAH/grlc}
}
```
while the Software Heritage bibtex format looks something like this:
```bibtex
@software {delebecque:hal-02090402,
title = {Scilab},
author = {Delebecque, Fran{\c c}ois and Gomez, Claude and Goursat, Maurice
and Nikoukhah, Ramine and Steer, Serge and Chancelier, Jean-Philippe},
date = {1994},
institution = {Inria},
license = {Scilab license},
hal_id = {hal-02090402},
hal_version = {v1},
url = {https://www.scilab.org/},
abstract = {Software for Numerical Computation freely distributed.},
repository= {https://github.com/scilab/scilab},
}
```
The bibtex extension introduces four entry types: `@software`, `@softwareversion`, `@softwaremodule`, `@codefragment`, and the user needs to include an additional latex package ` \usepackage{software-biblatex}`.

**Comment by jspaaks** [comment]
I would prefer to stick with mainstream practices, and practices supported by some of the reference managers out there. Am I correct in saying that biblatex-software is not currently well known? Haven't done much LaTeX of late.

Sidenote, it also seems tied closely to SHA and HAL.

**Comment by c-martinez** [comment]
Chicken & egg problem, right? I don't think biblatex-software is very well know (yet), but it will not get well known unless users (both citation providers & authors) provide it.

I thought this would be an extra reference manager file format option. Currently we have bibtex, Endnote, RIS, etc, we could have bibtex, bibtex (software), Endnote, etc.

**Comment by jspaaks** [comment]
Sorry, I don't think this is the right way to go.
