### ISSUE TITLE
+ not allowed in short statement

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#398]
I tried to put `C++` in the short statement field in the admin site, but got a `should match pattern "^[a-zA-Z0-9,.;:\-_ '’]+$"` error.

**Comment by jspaaks** [comment]
Thanks for the report, we'll update it (but don't hold your breath, development is pretty slow these days).

**Comment by sverhoeven** [comment]
Plusses are now allowed in short statement of a software item.
