### ISSUE TITLE
Add programming languages Julia and NCL

### ISSUE THREAD

**Issue by Peter9192** [research-software-directory/research-software-directory#401]
The RSD features a programming languages section, but the options to choose from do not include Julia or [NCL](https://www.ncl.ucar.edu/). We use/support these languages in ESMValTool, so it would be nice if they could be added.

**Comment by jspaaks** [comment]
Hi Peter, thanks for the report. It's not difficult to add this, but as we are currently a bit short on staff, it may take a while for this to be available in production.
