### ISSUE TITLE
In the main README, offer the shortcut of running with rsd-secrets.env.example

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#416]
So first time users can immediately see a result, even if it is not immediately what they want for themselves.

```
git clone <the repo> .
cp rsd-secrets.env.example rsd-secrets.env
docker-compose build
source rsd-secrets.env
docker-compose up -d
```

**Comment by sverhoeven** [comment]
You will have to explain that the admin interface and harvesting will not work due to missing tokens.

**Comment by jspaaks** [comment]
Done in https://github.com/research-software-directory/research-software-directory/tree/b07de659b0036d13a45bae53203005e9c4785dd0, closing
