### ISSUE TITLE
localhost deployment: Your connection is not private

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#418]
After following instructions to try it locally I tried to visit the site as instructed at https://github.com/research-software-directory/research-software-directory/#verifying-the-local-installation . Instead of seeing the rsd home page I was treated with a `NET::ERR_CERT_AUTHORITY_INVALID` error. I could get go further by toggling advanced and proceeding to localhost (unsafe).

This error is not documented or mitigated, which is what I expected.

**Comment by jspaaks** [comment]
See also duplicate issues: #418, #429,  #432

**Comment by fdiblen** [comment]
this can be a useful source:
https://kinsta.com/knowledgebase/neterr-cert-authority-invalid/

**Comment by jspaaks** [comment]
Do we need anything else besides the now documented fact that the certificate error is expected?
