### ISSUE TITLE
OAI-PMH api endpoint does not work immediately

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#420]
At https://github.com/research-software-directory/research-software-directory/#oai-pmh a example url http://localhost/oai-pmh?verb=ListRecords&metadataPrefix=datacite4 is given. When visiting the example url I get redirected back to home page (`/`). I expected to get a XML document. 

I think this due to empty `docker-volumes/oaipmh-cache/` directory.
After running `docker-compose exec harvesting python app.py harvest metadata`, the example url did work.

The metadata harvest command should be documented and/or scheduled.

**Comment by jspaaks** [comment]
There's some text here https://github.com/research-software-directory/research-software-directory/tree/2c2a23281f5158b8bcd4906d89aa7eb4dc5e601d/harvesting#usage

and schedule is here http://localhost/schedule, documented here: https://github.com/research-software-directory/research-software-directory/tree/2c2a23281f5158b8bcd4906d89aa7eb4dc5e601d#harvesting-schedule

The challenge is of course finding this particular piece of information in the sea of other pieces. And, it doesn't say anything about  the fact the OAI-PMH files are not immediately there.

**Comment by sverhoeven** [comment]
OK, so this was due to my `harvest all` dying before it got to oaipmh harvester. When `harvest all` runs completely the dir is filed and endpoints work correctly.
