### ISSUE TITLE
Separate documentation page

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#421]
The amount of information in the main README is too much. It would help to have separate guides (readthedocs or github.io) for users and the developers.

**Comment by jspaaks** [comment]
Let's first work on separating the content into their own READMEs under `docs/` though.

**Comment by fdiblen** [comment]
# Research Software Directory TOC

- Short description
- Feature list
- TL;DR (without changes)
- Pointer to configuring
- Customization

Use cases

- I want to run Research Software Directory with my own data sources
- I want to enter my own data
- I want to change look and feel

- I want to contribute (code)
- Making a release
- Finding your way: Research Software Directory services

- I want to host it online
  - instructions using docker-compose
  - deploy to AWS
  - how to do backups
  - updating the prod. instance
- I am concerned about security

**Comment by jspaaks** [comment]
Done in https://github.com/research-software-directory/research-software-directory/tree/b07de659b0036d13a45bae53203005e9c4785dd0, closing
