### ISSUE TITLE
Use GitHub cli

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#424]
GitHub now has an [official cli](https://github.com/cli/cli).
Use of GitHub cli can be considered.
For example:
gh repo fork research-software-directory/research-software-directory

**Comment by sverhoeven** [comment]
I think using `git` is good enough. Do not think we can use any of the other GH CLI commands to our benefit.

**Comment by jspaaks** [comment]
Agree with Stefan. People who have the cli tool will look at the instructions and do the fork using the cli if they prefer. Vice versa, we should not bother people who do not have the cli.

Closing this issue.
