### ISSUE TITLE
Node version is outdated

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#425]
It will be good to use latest stable version of Node which is 14.13.0.
Some components uses an old version of Node. https://github.com/research-software-directory/research-software-directory/blob/master/admin/Dockerfile 

There are some important security fixes in this release.  https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2020-06-02-version-1440-current-targos

**Comment by jspaaks** [comment]
Mostly done in PR #467, still awaiting PR #473.

**Comment by jspaaks** [comment]
PR was merged, closing
