### ISSUE TITLE
Security warning when running locally

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#429]
When trying locally, my web browser warns about the security due to the SSL certificate. Some developers / users maybe reluctant to continue if they are not familiar with this.

![rsd_ssl_warning](https://user-images.githubusercontent.com/144492/94815973-75070100-03fb-11eb-8250-aa590dc50c8d.png)

**Comment by jspaaks** [comment]
See also duplicate issues: #418, #432

**Comment by fdiblen** [comment]
Closing as this is a duplicate of #418
