### ISSUE TITLE
Windows installation instructions: using rsd-secrets.env

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#431]
From what I understand, you cannot use an env file directly in Windows, through cmd or powershell.
In Powershell you can however, use a PS script.
For this I had to create a file called rsd-secrets.ps1 based on the env file and reformat the contents in the following way:
```PowerShell
$Env:COMPOSE_PROJECT_NAME='rsd'
$Env:DOMAIN='localhost'
...
```
note that all values need quotes in PS script.

Execute in PS like you would any other script:
```PowerShell
.\rsd-secrets.ps1
```

**Comment by jspaaks** [comment]
Note our use of rsd-secrets.env will change with https://github.com/research-software-directory/research-software-directory/pull/482

**Comment by jspaaks** [comment]
Also, It's good to note that Windows (and Mac) are not supported platforms.

**Comment by jspaaks** [comment]
@cwmeijer this issue can be closed right? Since we're [now](https://github.com/research-software-directory/research-software-directory/tree/cfb86c3f193fcb750736016b9cb973e44953823d) using the special `.env` file which also works on Windows?

**Comment by cwmeijer** [comment]
yes!
