### ISSUE TITLE
Use GH Actions

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#436]
We should replace Travis with GH Actions

**Comment by jspaaks** [comment]
It would also be useful to periodically test if we can build the thing; this would help avoid having to make last minute fixes before presentations and such (e.g. #404). 

See https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

Not sure if we can be notified on fail.

**Comment by jspaaks** [comment]
Run integration tests on a daily schedule: PR https://github.com/research-software-directory/research-software-directory/pull/478

**Comment by jspaaks** [comment]
PR was merged, closing
