### ISSUE TITLE
frontend still uses project.principalInvestigator

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#452]
But that has been replaced by team[].role == "Principal investigator". 

At least two options to fix:
1. Update the template with some processing, something like `[t for t in project.team if t.role == "Principal investigator"][0]["name"]`
1. (probably cleaner) update the software_cache method such that it adds `.principalInvestigator` to the `project_cache` document as a derived property

**Comment by eriktks** [comment]
I tried to fix this but the project data (I think from `admin/src/fixtures/data.json`) contains no team information, but it does contain principalInvestigator. There is a file `frontend/mocks/software_cache.json` with a team field for projects but the field is always empty in the file.

Is this issue dependent on future fixes or should some other data be downloaded?

**Comment by jspaaks** [comment]
Note: I expect both of those files to be out of date.

Generally speaking, it has been difficult keeping the test data up to date. What about adding a test that periodically checks if the sample data is still the same as what is used in testing?

I don't think testing against live systems will be helpful, because 

1. the data there will change;
1. its data version may be old compared to master branch

**Comment by eriktks** [comment]
My plan is to update the template. Adding a derived property to the document would duplicate data and duplicate ways to interface the data.

**Comment by eriktks** [comment]
See also issue #575 which removes the references PI from the related projects

**Comment by eriktks** [comment]
This issue has been made obsolete by issue #575
