### ISSUE TITLE
Replace `rsdnlesc/docker-term-letsencrypt` image

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#465]
The image was made by @Tommos0 in the past, but has not been updated in a long time.

We could replace it with [caddy](https://hub.docker.com/_/caddy) which handles the HTTPS cert for us and is officially supported image by Docker inc.

**Comment by jspaaks** [comment]
In the meantime, I forked @Tommos0'es repo to this org just in case.

**Comment by sverhoeven** [comment]
Duplicate of #339
