### ISSUE TITLE
Use slug in project URL

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#479]
Currently a project URL looks like `https://localhost/projects/816` it would be nice a editor changeable slug could be used. For example `https://localhost/projects/AMUSE`. Slug is already used for software URLs.

**Comment by jspaaks** [comment]
Agree this would be nice, if we can set some rules on slugs that is. Also `slugs` could be an array.

**Comment by sverhoeven** [comment]
We could also go for `https://localhost/projects/816-AMUSE` where everything after `-` is discarded by route handler. 

I would not go for array of slugs, one is already enough for making a pretty url.

**Comment by jspaaks** [comment]
PR #555 was merged, closing.
