### ISSUE TITLE
make node version less specific?

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#483]
from https://github.com/research-software-directory/research-software-directory/pull/473#issue-501627085

node version is now consistent throughout the whole stack
It's specified down to patch version, which may be a bit too much. Accroding to this https://hub.docker.com/_/node?tab=description&page=1&name=node , we could do `14.13-alpine` or even `14-alpine`.

**Comment by eriktks** [comment]
Solved by PR #543
