### ISSUE TITLE
Mentions block too wide

### ISSUE THREAD

**Issue by eriktks** [research-software-directory/research-software-directory#486]
Because of its width and dark color, the mentions block on a software page looks like the end of the web page which may prevent users from scrolling further (it has that effect on me). Making it less wide would help

**Comment by jspaaks** [comment]
Hi Erik, I would like to stick to a design that is consistent with the software pages for now. I propose to wait and see how the project pages look once we have a bit more data in them, and we implement the 'Split into Output and Impact sections' behavior.
