### ISSUE TITLE
Add superlint

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/research-software-directory#488]
It would be nice to have linting for the markdown files so that we can check broken links.

**Comment by sverhoeven** [comment]
We can use https://github.com/peter-evans/liche-docker to check links in Markdown

**Comment by jspaaks** [comment]
Specifically for markdown link checking, we used markdown link checker in the past https://github.com/ADAH-EviDENce/evidence/actions?query=workflow%3A%22Check+Markdown+links%22

I made a separate issue out of this (#495), since it is not covered by the superlinter.

**Comment by jspaaks** [comment]
Regarding the superlinter, retro-fitting linters usually generates a lot of work. This may lead to PRs that are very big. Perhaps we can divide the work a bit better by using superlinter's FILTER_REGEX_EXCLUDE, initially excluding all first-order directories, then make issues for enabling linting for each one.

**Comment by jspaaks** [comment]
Both the link checker and github superlinter have been added. Check superlinter progress here #618. Closing this issue.
