### ISSUE TITLE
data entry February 2018

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#49]
The data quality on research-software.nl could be better/more complete. 

Let's spend some time (**3 hours** or so) filling in data according to the plan outlined below.

# Plan

1. Make sure your membership of the NLeSC organization is set to public [here](https://github.com/orgs/NLeSC/people) (if it hasn't, use the dropdown next to your name)
1. Check the list of software packages below to find if you were assigned somewhere. The list below is not set in stone; feel free to switch assigned packages with coworkers if that makes more sense. For those who were not assigned, browse through the packages that were assigned to ``[object BSON]`` or ``undefined`` and see if you are the person that should be listed there (then make any necessary changes).
1. For every package where you were assigned,
    1. Consider if the package could be useful for others. Ignore the (supposed) engineering quality of the package when judging this. Our RSD should only include packages that we made significant contributions to. Adjust the **published** button accordingly.
    1. Verify that all fields have been filled in. Some fields require special attention:
        1. **Brand name**: regard this as a brand name for the software, similar to e.g. Coca-Cola; You don't order a 'Coca-Cola-company/Coca-Cola:v.3.4.2' now do you? You'd order a Cola or perhaps a Coke, so those latter two are good brand names, the former isn't. Futhermore, it's generally a bad idea to include project names in the 'Brand name' field.
        1. The short **software statement**, the **bullet point questions** and the **read more** text: make sure to use general/inclusive language. Stay away from project names and abbreviations. Also, it's perfectly OK to leave out specific details or exceptions here.
        1. **Getting started**: this should link to a place where the first steps to get started with the software are explained, e.g. the first chapter of a tutorial.
        1. **testimonial** and **testimonialBy**: find somebody (preferably from your project) who uses the software, and let them say what it helps them do. In my experience, the quickest way to get such quotes is to make them yourself, and then ask the testimonialBy person if they agree with having said that (and if it's OK to publish the fact that they did so on our website).
    1. Citation: the preferred way to include CITATION information is to have a file named CITATION.cff in your GitHub repository. We harvest those files from the repository on GitHub. CITATION.cff files are YAML files.
       1. Look [here](http://www.yamllint.com/) to validate whether the text of your CITATION.cff file is valid YAML.
       1. Read [this](https://github.com/citation-file-format/schema) information to set up validation of your CITATION.cff file with respect to the citation-file-format specification (find the full spec [here](https://citation-file-format.github.io/versions/)).
       1. For an example, look at [this file](https://github.com/NLeSC/mcfly/blob/master/CITATION.cff).
# Questions

If you have **questions**, post them under this issue.

# Assignment list

- [ ] [object BSON] https://admin.research-software.nl/software/fastmlc 
- [ ] [object BSON] https://admin.research-software.nl/software/mdstudio 
- [x] [object BSON] https://admin.research-software.nl/software/qtl-tableminer 
- [x] a.kuzniar https://admin.research-software.nl/software/fairdatapoint 
- [x] a.kuzniar https://admin.research-software.nl/software/linked-data-platform-for-animal-breeding-genomics 
- [x] a.kuzniar https://admin.research-software.nl/software/linked-data-platform-for-plant-breeding-genomics 
- [x] a.kuzniar https://admin.research-software.nl/software/siga-py 
- [x] a.sclocco https://admin.research-software.nl/software/aa-alert-integration 
- [x] a.sclocco https://admin.research-software.nl/software/aa-alert-snr 
- [x] a.sclocco https://admin.research-software.nl/software/amber 
- [x] a.sclocco https://admin.research-software.nl/software/astrodata 
- [x] a.sclocco https://admin.research-software.nl/software/dedispersion 
- [ ] b.vanwerkhoven https://admin.research-software.nl/software/kernel_tuner 
- [ ] b.weel https://admin.research-software.nl/software/boatswain 
- [ ] b.weel https://admin.research-software.nl/software/regis 
- [x] c.martinez https://admin.research-software.nl/software/beyond-the-book 
- [x] c.martinez https://admin.research-software.nl/software/common-sense 
- [x] c.martinez https://admin.research-software.nl/software/grlc 
- [x] c.martinez https://admin.research-software.nl/software/shifting-concepts-through-time 
- [x] c.martinez https://admin.research-software.nl/software/the-crowdtruth-framework 
- [x] c.meijer https://admin.research-software.nl/software/mcfly 
- [ ] d.remenska https://admin.research-software.nl/software/root-conda-recipes 
- [x] d.vankuppevelt https://admin.research-software.nl/software/case-law-app 
- [x] d.vankuppevelt https://admin.research-software.nl/software/caselawanalytics 
- [ ] e.ranguelova https://admin.research-software.nl/software/octseg 
- [ ] e.ranguelova https://admin.research-software.nl/software/salient-region-detectors 
- [ ] e.ranguelova https://admin.research-software.nl/software/salientdescriptor-matlab-imvip 
- [ ] e.ranguelova https://admin.research-software.nl/software/salientdetector-matlab 
- [x] e.tjongkimsang https://admin.research-software.nl/software/finding-journalists 
- [x] e.tjongkimsang https://admin.research-software.nl/software/online-behaviour-machine-learning 
- [x] e.tjongkimsang https://admin.research-software.nl/software/twinl-website-code 
- [x] e.tjongkimsang https://admin.research-software.nl/software/twiqs.nl 
- [x] f.diblen https://admin.research-software.nl/software/spot-desktop-app 
- [x] f.diblen https://admin.research-software.nl/software/spot 
- [x] h.spreeuw https://admin.research-software.nl/software/sagecal 
- [x] i.pelupessy https://admin.research-software.nl/software/amuse 
- [x] j.attema https://admin.research-software.nl/software/pattyanalytics 
- [x] j.attema https://admin.research-software.nl/software/python-pcl 
- [x] j.attema https://admin.research-software.nl/software/xtas 
- [ ] j.hidding https://admin.research-software.nl/software/escatter-pyelsepa 
- [ ] j.hidding https://admin.research-software.nl/software/hypercanny 
- [ ] j.hidding https://admin.research-software.nl/software/noodles 
- [ ] j.hidding https://admin.research-software.nl/software/pyxenon 
- [ ] j.maassen https://admin.research-software.nl/software/magnesium 
- [x] j.maassen https://admin.research-software.nl/software/xenon 
- [x] j.spaaks https://admin.research-software.nl/software/differential-evolution 
- [x] j.spaaks https://admin.research-software.nl/software/google-earth-toolbox-for-matlab 
- [x] j.spaaks https://admin.research-software.nl/software/matrix-of-scatter 
- [x] j.spaaks https://admin.research-software.nl/software/metrochartjs 
- [x] j.spaaks https://admin.research-software.nl/software/mmsoda-toolbox-for-matlab 
- [x] j.spaaks https://admin.research-software.nl/software/punchcardjs 
- [x] j.spaaks https://admin.research-software.nl/software/research-software-directory 
- [x] j.spaaks https://admin.research-software.nl/software/spiraljs 
- [x] j.vanderzwaan https://admin.research-software.nl/software/cptm 
- [x] j.vanderzwaan https://admin.research-software.nl/software/embodied-emotions-scripts 
- [x] j.vanderzwaan https://admin.research-software.nl/software/nlppln 
- [x] j.vanderzwaan https://admin.research-software.nl/software/ochre 
- [x] j.vanderzwaan https://admin.research-software.nl/software/recipy 
- [x] j.vanderzwaan https://admin.research-software.nl/software/rig 
- [x] j.vanderzwaan https://admin.research-software.nl/software/scriptcwl 
- [x] j.vanderzwaan https://admin.research-software.nl/software/texcavator 
- [x] j.vanderzwaan https://admin.research-software.nl/software/topic-coherence-for-dutch 
- [x] l.ridder https://admin.research-software.nl/software/3d-e-chem-sygma 
- [x] l.ridder https://admin.research-software.nl/software/magma 
- [x] l.ridder https://admin.research-software.nl/software/qmflows 
- [x] l.veen https://admin.research-software.nl/software/cerise-client 
- [x] l.veen https://admin.research-software.nl/software/cerise 
- [x] m.vanmeersbergen https://admin.research-software.nl/software/ahn2webviewer 
- [x] m.vanmeersbergen https://admin.research-software.nl/software/cesium-ncwms 
- [x] m.vanmeersbergen https://admin.research-software.nl/software/pattyvis 
- [ ] m.vanmeersbergen https://admin.research-software.nl/software/potree 
- [x] m.vanmeersbergen https://admin.research-software.nl/software/storyteller 
- [ ] n.drost https://admin.research-software.nl/software/ewaterleaf 
- [ ] n.drost https://admin.research-software.nl/software/sfm 
- [x] p.bos https://admin.research-software.nl/software/hadrianus-scripts 
- [x] p.bos https://admin.research-software.nl/software/pidilib 
- [x] p.bos https://admin.research-software.nl/software/roofit 
- [x] r.goncalves https://admin.research-software.nl/software/datavaults 
- [x] r.goncalves https://admin.research-software.nl/software/monetdb 
- [x] r.goncalves https://admin.research-software.nl/software/sherlock-emma 
- [x] r.vanharen https://admin.research-software.nl/software/frbcat-web 
- [x] r.vanharen https://admin.research-software.nl/software/frbcatdb 
- [ ] r.vanharen https://admin.research-software.nl/software/netcdf2littler 
- [ ] r.vanharen https://admin.research-software.nl/software/wrfpy 
- [ ] r.vannieuwpoort https://admin.research-software.nl/software/eastroviz 
- [ ] s.georgievska https://admin.research-software.nl/software/cclustera 
- [ ] s.georgievska https://admin.research-software.nl/software/dive 
- [x] s.verhoeven https://admin.research-software.nl/software/3d-e-chem-knime-pharmacophore 
- [x] s.verhoeven https://admin.research-software.nl/software/3d-e-chem-knime-plants 
- [x] s.verhoeven https://admin.research-software.nl/software/3d-e-chem-vm 
- [x] s.verhoeven https://admin.research-software.nl/software/cartodb-docker-image 
- [x] s.verhoeven https://admin.research-software.nl/software/chemical-analytics-platform 
- [x] s.verhoeven https://admin.research-software.nl/software/eecology-annotation 
- [x] s.verhoeven https://admin.research-software.nl/software/eecology-tracker-calendar 
- [x] s.verhoeven https://admin.research-software.nl/software/extjs-datetime 
- [x] s.verhoeven https://admin.research-software.nl/software/knime-archetype 
- [x] s.verhoeven https://admin.research-software.nl/software/knime-gpcrdb 
- [x] s.verhoeven https://admin.research-software.nl/software/knime-klifs 
- [x] s.verhoeven https://admin.research-software.nl/software/knime-molviewer 
- [x] s.verhoeven https://admin.research-software.nl/software/massivepotreeconverter 
- [x] s.verhoeven https://admin.research-software.nl/software/osmium 
- [x] s.verhoeven https://admin.research-software.nl/software/surf-eds-one-button-compute 
- [x] s.verhoeven https://admin.research-software.nl/software/xenon-cli 
- [x] s.verhoeven https://admin.research-software.nl/software/xenon-grpc 
- [ ] undefined https://admin.research-software.nl/software/3d-e-chem-knime-kripodb 
- [ ] undefined https://admin.research-software.nl/software/3d-e-chem-knime-python-node-archetype 
- [x] undefined https://admin.research-software.nl/software/3d-e-chem-knime-python-wrapper 
- [ ] undefined https://admin.research-software.nl/software/3d-e-chem-knime-sygma 
- [ ] undefined https://admin.research-software.nl/software/3d-e-chem-kripodb 
- [ ] undefined https://admin.research-software.nl/software/ahn-pointcloud-viewer-ws 
- [x] undefined https://admin.research-software.nl/software/allelic-variation-explorer 
- [ ] undefined https://admin.research-software.nl/software/andi-frontend 
- [ ] undefined https://admin.research-software.nl/software/andi-ocpu 
- [ ] undefined https://admin.research-software.nl/software/andi-webservices 
- [ ] undefined https://admin.research-software.nl/software/arena-crowds 
- [ ] undefined https://admin.research-software.nl/software/biographynet-demonstrator 
- [ ] undefined https://admin.research-software.nl/software/biographynet-language-analysis-pipeline 
- [ ] undefined https://admin.research-software.nl/software/breed4food-rdf-graphs-pig 
- [ ] undefined https://admin.research-software.nl/software/casacore 
- [ ] undefined https://admin.research-software.nl/software/cesium 
- [ ] undefined https://admin.research-software.nl/software/clustit 
- [x] undefined https://admin.research-software.nl/software/collatex 
- [ ] undefined https://admin.research-software.nl/software/complearn 
- [ ] undefined https://admin.research-software.nl/software/dales 
- [ ] undefined https://admin.research-software.nl/software/dalesview 
- [ ] undefined https://admin.research-software.nl/software/ece2cmor 
- [ ] undefined https://admin.research-software.nl/software/eecology-cartodb 
- [ ] undefined https://admin.research-software.nl/software/eecology-classification 
- [x] undefined https://admin.research-software.nl/software/eecology-sms-reciever 
- [x] undefined https://admin.research-software.nl/software/embodied-emotions-multi-label-dataset 
- [ ] undefined https://admin.research-software.nl/software/gpu-kernels-bhattacharya-distance-two-point-sets 
- [ ] undefined https://admin.research-software.nl/software/gpu-kernels-for-gausstransform 
- [ ] undefined https://admin.research-software.nl/software/km3net-real-time-detection-of-neutrinos-using-gpus 
- [x] undefined https://admin.research-software.nl/software/knime-plugin-distance-bitvector-modified-tanimoto 
- [x] undefined https://admin.research-software.nl/software/knime-sstea 
- [x] undefined https://admin.research-software.nl/software/knime-testflow 
- [ ] undefined https://admin.research-software.nl/software/langident 
- [ ] undefined https://admin.research-software.nl/software/linked-data-platform-for-structural-variants-in-human-cancer-genomes 
- [ ] undefined https://admin.research-software.nl/software/mogli 
- [ ] undefined https://admin.research-software.nl/software/newsreader-component-wrappers 
- [ ] undefined https://admin.research-software.nl/software/newsreader-hadoop 
- [ ] undefined https://admin.research-software.nl/software/newsreader-hbase 
- [ ] undefined https://admin.research-software.nl/software/prnu-gpu-desktop 
- [ ] undefined https://admin.research-software.nl/software/rascal 
- [ ] undefined https://admin.research-software.nl/software/rdkit 
- [ ] undefined https://admin.research-software.nl/software/sherlock-dive 
- [ ] undefined https://admin.research-software.nl/software/storyteller-with-querybuilder 
- [ ] undefined https://admin.research-software.nl/software/summer-in-the-city-heatwave-map 
- [ ] undefined https://admin.research-software.nl/software/timbuctoo 
- [ ] undefined https://admin.research-software.nl/software/wps-configuration 
- [ ] undefined https://admin.research-software.nl/software/wrf-configuration 
- [ ] undefined https://admin.research-software.nl/software/zerotier-portal-backend 
- [ ] undefined https://admin.research-software.nl/software/zerotier-portal 
- [x] v.hees https://admin.research-software.nl/software/compressing-the-sky 
- [x] v.hees https://admin.research-software.nl/software/eeg-epilepsy-diagnosis 
- [x] v.hees https://admin.research-software.nl/software/wadpac-ggir

**Comment by sonjageorgievska** [comment]
Hi, during the last sprint we had the following discussion: should every possible repository/release end up in the RSD? Many of us have written code that is highly specific to the scientific problem at hand, not to mention scripts that analyze messy data for the purpose of coming up with a research direction. Even if those scripts were used in a publication (so they are FAIR), is not all this code going to confuse the random visitor of the RSD site (i.e. isn't it adding too much noise?)

**Comment by jspaaks** [comment]
we want to do two things:

1. keep track of our output
    - We do this through Zotero, so by all means, if you think something qualifies as output, put it in there. Even highly specific code qualifies for this. Also, it's perfectly OK to put multiple versions/releases of the same 'brand' in Zotero (but not the Research Software Directory, see below).
1. encourage re-use of software packages that we developed/were heavily involved with. 
    - We do this through our Research Software Directory at https://research-software.nl/. The Research Software Directory is all about presentation, so we need to make sure that we do not fill it with noise, as you so aptly put it.

**Comment by sverhoeven** [comment]
Hmm, checkboxes are disabled for me, I think I need to more permission on the repo.

**Comment by sverhoeven** [comment]
I wrote a script at https://github.com/3D-e-Chem/release2cff to generate a CITIATION.cff from a Zenodo GitHub Release DOI.

**Comment by c-martinez** [comment]
About testimonials -- is there an example we can show people? "Hey, I wrote this, can I say you said it and put it on our website. It will look like this"

**Comment by jspaaks** [comment]
- @sverhoeven 
    - checkboxes: as a test, I've made you an outside collaborator on the landing-page repo, let me know if that changes anything.
    - script: perhaps the good folks over at https://github.com/citation-file-format would be interested in this?
- @c-martinez: 
    - short answer: https://www.research-software.nl/software/shifting-concepts-through-time
    - long answer: testimonials currently only show up in the website when there are projects associated with a tool (see https://github.com/research-software-directory/landing-page/issues/68). You can check the api link to see what's in a given tool's json data, e.g. https://api.research-software.nl/software/shifting-concepts-through-time. Currently, the testimonial data is contained in the ``testimonial`` and ``testimonialBy`` keys (use the filtering capabilities of your browser to find them easily, if they exist), but know that this will likely change, see for example the [fixtures](https://github.com/research-software-directory/schema-nlesc/blob/93e4688db83b742805c735d9926cb68c880e8502/schema-fixtures/software1.json#L112-L130) we have for the new simplified data model we are working on in issue https://github.com/research-software-directory/landing-page/issues/36.

**Comment by egpbos** [comment]
The Get Started button downloads the HTML page of the link I put in the Getting Started url field for RooFit. A bit strange, or is it just me?
https://research-software.nl/software/roofit

**Comment by egpbos** [comment]
I see now that two projects that we filled things in for during the sprint now have a lot of empty fields! What happened?

https://admin.research-software.nl/software/pidilib
https://admin.research-software.nl/software/hadrianus-scripts

**Comment by egpbos** [comment]
Oh wait, for pidilib the problem is that it's a duplicate for this one:
https://admin.research-software.nl/software/pidimehs-library
Could you please remove pidilib @jspaaks or @Tommos0?

**Comment by egpbos** [comment]
I also still can't check boxes, but I finished RooFit and Hadrianus scripts, and as mentioned above, pidilib is a duplicate that should be removed.

**Comment by jspaaks** [comment]
@egpbos, thanks for the input.

1. https://research-software.nl/software/roofit 'get started' link looks good to me as it is now
1. remove pidilib: https://github.com/research-software-directory/landing-page/issues/73
1. does https://admin.research-software.nl/software/pidimehs-library have an associated github repo?

**Comment by egpbos** [comment]
2. I still have the issue. I tried making my organisation membership public, that didn't help either.
4. No, it's on bitbucket.
5. That is correct. I tried adding Wouter as a contributor, but his name doesn't seem to appear on the page...

**Comment by jspaaks** [comment]
5. might be due to caching because I did see his name. You can try appending ``?902739403`` to the url (where ``902739403`` should be a random string every time you want uncached results)

**Comment by egpbos** [comment]
5: never mind, I see it updated now. I also added some other collaborators. Would be nice if we could drag names in the list, but this is such a minor issue that I won't bother making an issue out of it ;) @Tommos0

**Comment by egpbos** [comment]
Ok, so actually there's another issue for RooFit. RooFit is part of the monolithic ROOT repository. ROOT has all its business properly straightened out, including, to my mild surprise, a CITATION.cff file. However, this is not the citation that should be used for RooFit, it is the general ROOT one. There should be a way to specify, I would say.

When done in a general way, i.e. a way to manually correct automatically retrieved fields, this could also be useful for when things are not on GitHub, like for the PIDIMEHS library which is on Bitbucket, but I'm sure there's other cases.

Maybe this should be a separate issue though?

**Comment by jspaaks** [comment]
@egpbos can you check/uncheck these?:

- [ ] the first item
- [ ] the second item

**Comment by egpbos** [comment]
Yep!

**Comment by jspaaks** [comment]
OK, I get your changes as well on my side, which did not seem to be happening with the table&checkbox combination. I think I'll just reformat the table to a list then.

**Comment by jspaaks** [comment]
@egpbos I just realized that your issue (1) about downloading the get started link might be a browser issue (I assume that was on Safari?). Or does it also happen on Chrome/Firefox?

**Comment by egpbos** [comment]
The get started link is working now, so it was probably a gremlin.

**Comment by jspaaks** [comment]
@dafnevk and others:

For those who are editing CITATION.cff files, note that the spec has support for name particles ('van', 'van der', 'de', etc) as well as name suffixes ('jr', 'IV', etc)

Corresponding keys are:

- ``name-particle``
- ``name-suffix``

see https://citation-file-format.github.io/assets/pdf/cff-specifications-1.0.3.pdf p12

**Comment by ridderl** [comment]
I added  CITATION.cff file to the github repo of  MAGMA, but now, when I try to download the citation on  https://www.research-software.nl/software/magma, I get “Failed - Server problem”. Does that mean something is wrong with the CITATION.cff ?

**Comment by jspaaks** [comment]
Hey Lars, I think the [quoted ``date-released``](https://github.com/NLeSC/MAGMa/blob/fb3d704c26bd4687dcba4b48fd5a14b6c2b9bea1/CITATION.cff#L18) in your ``CITATION.cff`` could be a problem. For future reference, the validator emits a rather cryptic message about this:
```
pykwalifire -s schema.yaml -d CITATION.cff -y cff
['%Y-%m-%d']
```
Admittedly, it also says 
```
 INFO - validation.valid
```
Would you unquote it so I can test? Also, be advised there might be additional problems (we have been fiddling with how we generate citation data).

**Comment by vincentvanhees** [comment]
Hey Jurriaan, I prefer not to include a CITATION.cff file to my repository. The repository represents an R library and R has it's own standardized way of including citation files to libraries, which is inside the 'inst' directory: [example from ggplot2](https://github.com/tidyverse/ggplot2/blob/master/inst/CITATION). 

The repository would get messy if there are mutiple citation files and I am also not sure whether CRAN (the PiPy for R) appreciates file formats that they do [not prescribe](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#CITATION-files). CRAN is very strict when it comes to adhering to their rules. Their citation file format is a simple text file.

**Comment by vincentvanhees** [comment]
for R packages best approach seems to be to create a CITATION.cff as described by Jurriaan, and then to add CITATION.cff to a .Rbuildignore file to prevent it from ending up in the package build. R and CRAN do not like cff files because R already has it's own CITATION file standard.

**Comment by jspaaks** [comment]
Thanks Vincent,
this seems like a good workaround.

**Comment by sverhoeven** [comment]
The cff generation tool has been moved to https://github.com/citation-file-format/doi2cff
