### ISSUE TITLE
project page results in http 500 error

### ISSUE THREAD

**Issue by eriktks** [research-software-directory/research-software-directory#496]
The frontend fails building a project page when the project data does not contain a starting date (KeyError: 'dateStart' on line 234 in /src/app/application.py)

**Comment by jspaaks** [comment]
I'm interested to know how do you trigger that bug though? Given that both `dateStart` and `dateEnd` are required keys?

https://github.com/research-software-directory/research-software-directory/blob/8094bbbba90b78e9c1a45e7abd0ddf154f01034c/backend/schemas/project.json#L228-L229

**Comment by eriktks** [comment]
I will try to find more context information. But basically I built the system, went to the local website, clicked on mcfly, got the software page, clicked on the project and got an Internal Server Error. One odd thing about my testing computer is that it currently has no outside Internet connection but I think that should not cause the error.

**Comment by sverhoeven** [comment]
Did you perform the data migration?
```
docker-compose exec database mongo rsd
```
And then copy paste content of https://github.com/research-software-directory/research-software-directory/blob/master/data-migration/data-migration-2.0.x-to-2.1.x.js in shell

**Comment by eriktks** [comment]
The data migration commands from Stefan solved the problem. Thanks!

**Comment by jspaaks** [comment]
For future reference, the API can also be used to check what properties you have:
- http://localhost/api/project/764
- http://localhost/api/project_cache/764 (same as the other link, but with all foreign keys resolved)
