### ISSUE TITLE
contact person boolean vs role

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#497]
A software item uses a boolean to signify that a contributor is the contact person. A project uses a role=contactperson to signify that a contributor is the contact person.  It would be nice to me if we treated contact person in the same way. So have either a boolean or use a role for both collections.

**Comment by jspaaks** [comment]
Considering we decided that it's no problem to have the same person as a contact person and as a team member, I suggest we remove the role `Contact person` from the enum, and introduce a boolean `isContactPerson` in the list of team members. This would be consistent with the software page's data model.

**Comment by jspaaks** [comment]
While you're at it changing the schema, combine with #479

**Comment by jspaaks** [comment]
PR #555 was merged, closing.
