### ISSUE TITLE
Fill project data for single project

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#498]
- [x] pick a good project 
- [x] fill data using admin interface
- [x] dump data to sample data

This is only for testing purposes of the new project page.

**Comment by jspaaks** [comment]
I suggest we try ABC-MUSE, since that is what the mock also uses. corporate site description here https://www.esciencecenter.nl/projects/abc-muse/, mockup here https://github.com/research-software-directory/research-software-directory/issues/407#issuecomment-708282600

**Comment by jspaaks** [comment]
PR was merged, closing.
