### ISSUE TITLE
Project page improvements

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#499]
- Maximum height for images to prevent huge images on the page (#502)
- Create progress bar to status section in side bar (#503)
- grey background for side bar (#505)
- full width for title and subtitle (side bar should move down a bit to align with top of image) (#506)
- Look for opportunities to make the 'feel' of the page more consistent with style for software page
- Use link icons in side bar (see software page; #507)
- Make the sidebar extend to the output/impact section (see Jason's mockup; #508)
- Mentions should be aligned with titles (this ties into the previous list item; #509)
- Style the contact person consistently with the mockup (#510)
- For all non-required field in the project schema, it should be tested that the page renders nicely with this data missing (#512). for instance:
  - no picture
  - related software (section should not render then)
  - related projects (section should not render then)
- respect the isPublished value (#513)
  - for the current project
  - related projects

**Comment by jspaaks** [comment]
I'll groom this into separate issues.
