### ISSUE TITLE
On the project pages, make the sidebar overlap the output/impact section

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#508]
For reference, 
- this is the state of the code base: https://github.com/research-software-directory/research-software-directory/tree/8094bbbba90b78e9c1a45e7abd0ddf154f01034c
- this is the mockup: https://github.com/research-software-directory/research-software-directory/issues/407#issuecomment-708282600

**Comment by fdiblen** [comment]
As we don't have the contact person block, it is not an issue anymore. Closing the issue

**Comment by sverhoeven** [comment]
Also if there is no impact and output the block below it needs to be slimmer causing less realestate for content.

**Comment by jspaaks** [comment]
Re https://github.com/research-software-directory/research-software-directory/issues/508#issuecomment-717256417: I think this was closed prematurely, as we still have the contact person block AFAIK.

However, I would suggest moving the contact person to be part of the Team section, so that section is laid out exactly like the Contributors section is on the software pages, and the overlap will no longer be an issue.

**Comment by jspaaks** [comment]
Is now part of #594, closing
