### ISSUE TITLE
On the project pages, Mentions should be aligned with titles

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#509]
There probably won't be enough space to have the list of mentions only in the middle one-third of the page content. Let's try to remove the indent of the section, such that the list of mentions can span the leftmost 2/3 of the content part of the project page.

For reference, 
- this is the state of the code base: https://github.com/research-software-directory/research-software-directory/tree/8094bbbba90b78e9c1a45e7abd0ddf154f01034c
- this is the mockup: https://github.com/research-software-directory/research-software-directory/issues/407#issuecomment-708282600

**Comment by cwmeijer** [comment]
blocked by #508

**Comment by fdiblen** [comment]
Closing as this is not an issue anymore. The contact person box is not overlapping anymore.
