### ISSUE TITLE
Check that project pages render correctly if non-required data is missing

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#512]
For all non-required field in the `project` schema, it should be tested that the page still renders nicely when these data are missing. For instance:

- no picture
- related software (section should not render then)
- related projects (section should not render then)

For reference, 
- this is the state of the code base: https://github.com/research-software-directory/research-software-directory/tree/8094bbbba90b78e9c1a45e7abd0ddf154f01034c
- this is the mockup: https://github.com/research-software-directory/research-software-directory/issues/407#issuecomment-708282600

**Comment by eriktks** [comment]
Issue closed after pull request #523 but might need to redo or repeat if the project page changes a lot
