### ISSUE TITLE
On the project pages, respect the isPublished value 

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#513]
For reference, 
- this is the state of the code base: https://github.com/research-software-directory/research-software-directory/tree/8094bbbba90b78e9c1a45e7abd0ddf154f01034c
- this is the mockup: https://github.com/research-software-directory/research-software-directory/issues/407#issuecomment-708282600

**Comment by jspaaks** [comment]
Hmm I thought I left a comment about the best way to do this but it seems to have been lost in the voids of cyberspace... let's try it once more:

https://github.com/research-software-directory/research-software-directory/blob/3cc2e16a91b53325ec206541678061013811401a/harvesting/cache.py#L72-L74

**Comment by sverhoeven** [comment]
A draft project (eg. project_id=1234) can appear in different places

1. In /api/project/1234, do we make distinction between anonymous or authenticated consumer?
1. In /api/project
1. In /api/project_cache/1234
1. In /api/project_cache
1. in project page /project/1234 , should it return 404 not found?
1. In project page as related project 
1. In project index page
1. In software page as related project

Where should the draft project be hidden?

**Comment by fdiblen** [comment]
implemented in #557
