### ISSUE TITLE
Make ABC-MUSE sample data more real

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#530]
Continuation of https://github.com/research-software-directory/research-software-directory/pull/529#pullrequestreview-511866715

The snakemake output blog is not tied with project, but gives DNA image, so I am OK to keep it. Also impact seems picked from other projects, which may look strange when demo-ed, but is better than nothing.

Looking at https://localhost/projects/764 some data can be made more real 

* project website: http://www.amusecode.org/ as it explains core of muse.
* Add amuse project (810) to related projects
* Amuse/Omuse/Hymuse do not use any Xenon software, please remove Xenon* + sv-callers
* Use grpc4bmi (adaptor), MUSCLE 3 (alternative) and ESMValTool (downstream) as related software

**Comment by sverhoeven** [comment]
Also fill affiliation of project team members

**Comment by sverhoeven** [comment]
Done
