### ISSUE TITLE
/projects/ and project/xyz

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#533]
In PR #498 it is discussed that projects and project should both be allowed (duplicates). I think projects and project are to different things. My opinion about the behavior:

| where | url | desired behavior | current behavior |
|---|---|---|---|
| API | .../api/project/ | list all the projects with their details as json | list all the projects with their details as json |
| API | .../api/project/xyz | return project details of project xyz as json | return project details of project xyz as json |
| pages | .../projects | render a list or index of all projects as html/css/etc (#534 will make it so) | redirect to / (similar #140 ) |
| pages | .../projects/xyz | show the project page of project xyz  | show the project page of project xyz |

I'm no REST expert, but I think this is how this is commonly done when doing REST.

**Comment by jspaaks** [comment]
https://www.tablesgenerator.com/markdown_tables#

**Comment by sverhoeven** [comment]
In REST APIs it is normal to use `/api/projects/xyx`, see for example https://jsonapi.org/recommendations/#urls-resource-collections. You pick a project from the projects resource collection. So I would like to keep `/api/projects/xyx`. 

The redirect for HTML pages seems overkill to me. Nobody will visit a project by guessing it, they will use the project index page or follow some other link. To me the ./projects/xyz redirect is not needed.

I am OK with having `/project/xyz` as is for human consumption.

**Comment by jspaaks** [comment]
BTW PR #498 should be https://github.com/research-software-directory/research-software-directory/pull/529#issuecomment-712245979

**Comment by jspaaks** [comment]
> So I would like to keep /api/projects/xyx

@sverhoeven I don't think we have that one ;). All the references to collections are singular, because that is apparently some kind of convention. I'm open to rethink this BTW, it has tripped me up many times

**Comment by sverhoeven** [comment]
You are right,  backend already uses singular names (backend/schemas/project.json) so switching to plural (projects) is more work.
