### ISSUE TITLE
collect data from esciencecenter.nl/projects to use as sample data

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#593]
minimally:
- project description
- team

optionally:
- partners
- related projects

**Comment by jspaaks** [comment]
My suggestion would be to add a second script here https://github.com/research-software-directory/research-software-directory/blob/fb1325b071d0a79570af7c74b1ce04930d73dc1a/data-migration/ , and use python's beautifulsoup (`bs4`) library, which could then be used to fill in the details of what was done by the script that's already there.

**Comment by jspaaks** [comment]
This is somewhat blocked by https://github.com/research-software-directory/research-software-directory/pull/555

**Comment by jspaaks** [comment]
PR #609

**Comment by eriktks** [comment]
Fixed by PR #609
