### ISSUE TITLE
on project pages, center sidebar logos, sized homogeneously

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#597]
groomed from #594

**Comment by jspaaks** [comment]
@cwmeijer, if you're working on this, please assign yourself

**Comment by cwmeijer** [comment]
Sized homogeneously is complicated to achieve.
In the ABC-Muse project we have 2 logos. One hase single line text, while the other has double. If we make the logos have equal height, obviously, the double lined Leiden logo seems tiny compared to single lined Utrecht. In the example below, I deliberately chose a relatively small ```max-height: 4rem```.
![image](https://user-images.githubusercontent.com/6087314/98694556-e37f9d00-2371-11eb-824a-33f7151f9e39.png)
When I use ```max-height: 15rem``` or above, the bottleneck for the images will no longer be their heights, but their widths will instead. This is the situation we already had, as the setting is ```40rem``` in master at the moment.
![image](https://user-images.githubusercontent.com/6087314/98694731-1c1f7680-2372-11eb-9be0-ca7b4b41f7cf.png)
Then of course, I can find some value where both will look OK and reasonably equal in size. For instance ```10em```:
![image](https://user-images.githubusercontent.com/6087314/98694963-61dc3f00-2372-11eb-804f-b7d6e6562d07.png)
This will of course be completely different using yet another logo.
We can also enforce the width to be 100%:
![image](https://user-images.githubusercontent.com/6087314/98696518-30fd0980-2374-11eb-9b06-dc694561252a.png)
I guess that doesn't look too bad with these two. It maybe has the best chances of working with other logos as well, even though these chances are still slim in my opinion. I'll make a PR using this method.

**I think, though, that this can only really be solved by uploading similarly sized and spaced logos carefully.**

**Comment by jspaaks** [comment]
Also I think the Leiden example logo has transparency around it that needs to be taken into account.

**Comment by cwmeijer** [comment]
How would you like to take transparency into account? Do you have an idea of the desired behavior? Labeled standup to discuss this.

**Comment by cwmeijer** [comment]
We want it like this:

![image](https://user-images.githubusercontent.com/6087314/98798612-5ccccd80-240e-11eb-91d5-ef9bf2903c45.png)
