### ISSUE TITLE
OAI-PMH metadata: 429 Too Many Requests for Zenodo URL

### ISSUE THREAD

**Issue by LourensVeen** [research-software-directory/research-software-directory#615]
On https://www.research-software.nl/software/muscle3, there's a header "Information for page maintainers", below which it reads:

OAI-PMH metadata:	429 Client Error: TOO MANY REQUESTS for url: https://zenodo.org/record/3258864
citation metadata:	OK

I guess I'm the page maintainer, but I have no clue what to do with this. That Zenodo link does point to the Zenodo page for the latest release of MUSCLE 3, and the RSD pulls data from Zenodo. So perhaps it's making a lot of requests? But what does that have to do with OAI-PMH, the RSD serves that, right? Is there anything I can do to fix this?

**Comment by jspaaks** [comment]
Nope dont have to do anything, just wait for the production environment to be updated :) Thanks for going through the effort of notifying us though, we appreciate that!
