### ISSUE TITLE
Don't open project link in new tab

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#621]
I don't expect links to the same web site to open in a new tab. Visiting a site I expect to stay in the active tab.

However on the projects index page and related projects on a software or project page open each project link in a new tab.
Can these links be changed so they open in the current tab?

**Comment by jspaaks** [comment]
didnt try but probably this line 

https://github.com/research-software-directory/research-software-directory/blob/4142d4901ddf1d85d7914eefd476fac0c96cb2a4/frontend/templates/project/project_index.html#L25

and this
https://github.com/research-software-directory/research-software-directory/blob/4142d4901ddf1d85d7914eefd476fac0c96cb2a4/frontend/templates/software/projects.html#L14

and this
https://github.com/research-software-directory/research-software-directory/blob/4142d4901ddf1d85d7914eefd476fac0c96cb2a4/frontend/templates/project/related_projects.html#L14

remove target=_blank
