### ISSUE TITLE
project index mockup

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#649]
![project-index-v4](https://user-images.githubusercontent.com/4558105/99524294-877fce80-2998-11eb-8147-cc30ef66ec9d.png)

**Comment by jspaaks** [comment]
![project-index-v4A](https://user-images.githubusercontent.com/4558105/99524332-936b9080-2998-11eb-8fd0-70a3401f06bd.png)

**Comment by sverhoeven** [comment]
`days/weeks X ago` is the number days ago the project was last updated.
