### ISSUE TITLE
Add data migration script with project startDate and endDate

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#650]
see xls sheet that @jmaassen has

update the data here https://github.com/research-software-directory/research-software-directory/blob/6cdcfc7fe829836fe806389179c58d22a565fecb/data-migration/2.x-to-3.x/add-project-dates.js

**Comment by jspaaks** [comment]
Hey Erik can you push your branch and make a draft PR so we can see how you're going? Thanks!

notify @eriktks

**Comment by eriktks** [comment]
fixed by PR #672
