### ISSUE TITLE
Add title, powered_by to project index page 

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#658]
Refs #649

**Comment by sverhoeven** [comment]
Can this issue be split, the search is more work then the title/powered_by.

**Comment by sverhoeven** [comment]
Search should look in
* title
* subtitle

Later if need also search in description

**Comment by jspaaks** [comment]
Split off adding a search bar into a new issue #663

**Comment by jspaaks** [comment]
PR #693 was merged, closing
