### ISSUE TITLE
Format project entries on index 

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#661]
Make them look like the mockup.
#649.

**Comment by sverhoeven** [comment]
The days/weeks text in bottom left corner are the days/weeks since last update of the project in the database.

@jspaaks Which mockup should we model after, the one with gray background or with border?

**Comment by sverhoeven** [comment]
pr #70 improved it, but still left for someone else to do

* increase image size
* have same height for each card
* push last updated ago and status to bottom of card
* icon in front of status

**Comment by sverhoeven** [comment]
The icons used in mockup can be found in Internets, watchout some need attribution. Where to put the atribution needs to figured out.

**Comment by jspaaks** [comment]
regarding image size, we'll use the same aspect ratio as in project pages (1024:600) (so no square images) Other than that, the gray background card mockup is the one we're aiming for https://github.com/research-software-directory/research-software-directory/issues/649#issue-745572789

**Comment by jspaaks** [comment]
> The icons used in mockup can be found in Internets, watchout some need attribution. Where to put the atribution needs to figured out.

I'd prefer to make our own or have more free icons. Or if that isn't possible given the time, no icons.

**Comment by jspaaks** [comment]
PR was merged, closing
