### ISSUE TITLE
Duplicate what directory is in docs/product.md

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#673]
As a person interested in the directory I would like to have one place on the GitHub repo where the product is explained.
Now the first chapter of `/README.md` and `/docs/product.md` trying to do the same thing. Can `docs/product.md` be merged into `/README.md` or removed?

Also the [docs/product.md](https://github.com/research-software-directory/research-software-directory/blob/3f3e988d3fbc3ed0aecf12831516fc0673d91d09/docs/product.md) ([docs/about.md](https://github.com/research-software-directory/research-software-directory/blob/3cb2c7447c9e9dc071f0dbbb13592fc9d82bfaa3/docs/about.md) in PR #671) is not linked to from anywhere. The `docs/images/20180627-webcapture-xenon.png` image is only used in  `docs/product.md`.

**Comment by jspaaks** [comment]
removed docs/about and image, closing
