### ISSUE TITLE
inconsistent slugs

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#71]
- https://research-software.nl/software/salient-region-detectors 
- https://research-software.nl/software/eecology-sms-reciever (consistent, but with typo)
- https://research-software.nl/software/wadpac-ggir

**Comment by jspaaks** [comment]
It's probably a lot easier to address this issue once we have moved past v2 milestone, because then we'll have a text field ``slug`` in the admin interface. Removing the issue from the milestone.

**Comment by jspaaks** [comment]
doesnt look like the slugs are picked up right, e.g. https://www.research-software.nl/software/salientdescriptor-matlab-imvip has slug ``salientdescriptor-matlab``.

**Comment by Tommos0** [comment]
Pages work both through `id` and `slug`, so https://www.research-software.nl/software/salient-descriptor-matlab also works. Perhaps we should by default link to the slug (if set) from the root page

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/frontend/commit/0cd2d1b558724896c524a6752c0e9b23f5068882
