### ISSUE TITLE
manually specify automatically harvested fields, like citation file

### ISSUE THREAD

**Issue by egpbos** [research-software-directory/research-software-directory#74]
Originally from here: https://github.com/research-software-directory/landing-page/issues/49#issuecomment-370729036

[RooFit](https://research-software.nl/software/roofit) is part of the monolithic ROOT repository. ROOT has all its business properly straightened out, including, to my mild surprise, a CITATION.cff file. However, this is not the citation that should be used for RooFit, it is the general ROOT one. There should be a way to specify, I would say.

When done in a general way, i.e. a way to manually correct automatically retrieved fields, this could also be useful for when things are not on GitHub, like for the [PIDIMEHS library](https://research-software.nl/software/pidimehs-library) which is on Bitbucket, but I'm sure there's other cases.

**Comment by jspaaks** [comment]
We used to have a free text field in the admin interface where you could put in the contents of what you would normally put in a CITATION.cff file, but we removed it for [this data entry round](#49) to encourage people to fix it in their GitHub repos. Also, support for Bitbucket should hopefully happen at some point (https://github.com/research-software-directory/landing-page/issues/43).

**Comment by egpbos** [comment]
Citations: that makes sense, except that in the case of a monolithic repo, it won't work. There's a lot to be said about monolithic repos, but it's a fact that they exist and if we ever do work on them we should still be able to make our work citable via this very nice and prominent button on the RSD (from my perspective, that button is one of the, if not *the*, main selling points of the RSD, actually).

Bitbucket: But then what about GitLab? Or projects that don't use either of these, maybe just a university SVN server?

Anyway, I'm sure you'll come up with a good solution, just wanted to put this corner-case on the radar.
