### ISSUE TITLE
Bug in default project Github link

### ISSUE THREAD

**Issue by CunliangGeng** [research-software-directory/research-software-directory#749]
The default project Github link is https://github.com/FIXME, that is a real account! How lucky the 'FIXME' guy is.  Thus it's necessary to change this default link to something else.

**Comment by jspaaks** [comment]
Thank you Cunliang for pointing these out. I don't think we'll be updating the FIXME links though, I was rather hoping that project managers / programme managers would be triggered by the data now pointing to a wrong value, rather than no value. Let's wait and see!
