### ISSUE TITLE
Incorrect mentions

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/research-software-directory#756]
On the [sv-channels](https://research-software.nl/software/sv-channels), two of the mentions [[1](https://doi.org/10.5281/zenodo.4593020)][[2](https://doi.org/10.5281/zenodo.4593061)] have incorrectly assigned type (i.e., _Journal articles_ instead of _Presentations_). After checking the corresponding records in Zotero, all items are of type _Presentation_. Do I miss something here? Thanks.

**Comment by jspaaks** [comment]
Looking at the DeepSV one, zotero has two copies of this item, both presentations. The admin interface has 3 DeepSV items, 2 presentations and 1 journalArticle. I went to https://www.research-software.nl/admin, selected 'mention' on the left hand side, typed DeepSV in the search bar and deleted the journalArticle. For the other link, I repeated the steps, just using the admin interface to delete the mentions that were duplicated in the RSD database.
