### ISSUE TITLE
estep.esciencenter.nl is still alive

### ISSUE THREAD

**Issue by tbkkr** [research-software-directory/research-software-directory#76]
Should go down/offline, or redirect automatically to research-software.nl (in case there are still external websites linking to eStep). 

The information on knowledge.esciencecenter.nl and research.esciencecenter.nl needs to be moved to be merged with the 2017 publication list on our corporate site. This includes both publications (peer reviewed and non-peer reviewed) and other forms of reports.

**Comment by tbkkr** [comment]
research.esciencecenter.nl can be removed. This content is now at: https://www.esciencecenter.nl/publications
Updates of this list should come from our Zotero database.

Van: Jurriaan H. Spaaks <notifications@github.com>
Verzonden: maandag 30 april 2018 14:18
Aan: research-software-directory/landing-page <landing-page@noreply.github.com>
CC: Tom Bakker <t.bakker@esciencecenter.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [research-software-directory/landing-page] estep.esciencenter.nl is still alive (#76)


  *   estep.esciencecenter.nl top page should be removed
  *   software.esciencecenter.nl works as it should (now points to research-software.nl)
  *   knowlegde.esciencecenter.nl: content should stay but probably not at knowlegde.esciencecenter.nl
  *   research.software.nl: strategy people should decide what to do with this @tbkkr<https://github.com/tbkkr>

**Comment by tbkkr** [comment]
@jspaaks I think this issue should be closed soon. estep.esciencecenter.nl should indeed be removed (it is still alive), although it preferably should redirect to esciencecenter.nl if possible. Same goes for knowledge./research.esciencenter.nl: remove (or direct to esciencecenter.nl).

**Comment by sverhoeven** [comment]
The collection of white papers on http://knowledge.esciencecenter.nl/ is not present somewhere else. 
So I don't really want to remove it.

**Comment by jspaaks** [comment]
Excellent. I did notice some referral traffic yesterday that came in via estep.esciencecenter.nl, that was probably you then.

**Comment by jspaaks** [comment]
Re the whitepapers, we could upload to Zenodo, but I think it's still good to have an overview somewhere with thumbnails like it is now.
