### ISSUE TITLE
Search for software "pronounced X"

### ISSUE THREAD

**Issue by c-martinez** [research-software-directory/research-software-directory#851]
When searching for software in the RSD, I've run into an issue where the name of the software (as it is written) does not match how the name is pronounced. Logically, typing the name as its pronounced, yields 0 results. This could be an issue for users who have heard of the software, but do not know how it is written.

Concrete example: I pointed a colleague to a tool called Garlic. Searching for Garlic in the RSD yielded 0 results. After clarifying ("oh, Garlic is written 'grlc'") they found it.

Additional example: searching for RSD in the RSD yields 0 results.

As a workaround, I could add 'Garlic' in the description, or as a keyword, but this doesn't seem like "the right way to to". 

Any ideas what is the best way to tackle this?

**Comment by jmaassen** [comment]
I think this issue is related to the current RSD implementation? Can you please resubmit you issue [here](https://github.com/research-software-directory/RSD-as-a-service/issues)?

**Comment by c-martinez** [comment]
Ha, good point -- created a [new issue there](https://github.com/research-software-directory/RSD-as-a-service/issues/784)
