### ISSUE TITLE
add project logo for download to "cite this software" section

### ISSUE THREAD

**Issue by RolfHut** [research-software-directory/research-software-directory#89]
For making (scientific) posters and other presentations it would be great if anyone that used a piece of (RSD) software used a consistent image. This could be facilitated by having the standard logo of the project available for download in the "cite this software" section.

I stumbled on this when looking for the the Amuse logo.

Rolf

PS not familiar with how to add labels issues, but this is clearly a "nice to have".

**Comment by jspaaks** [comment]
This is probably more at home as a download from the project page on github
