### ISSUE TITLE
My programming language is missing

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#94]
The list at https://github.com/research-software-directory/backend/blob/cfbd832e410a17488880dbf6beb62f39e58020c9/schemas/software.json#L441-L468 is incomplete.
Let me add my language or make the picklist bigger.

**Comment by jspaaks** [comment]
I don't want to add an ``Other`` since this does not help in searching by machines or reading by humans. If there is a language missing, I think people should make an issue. Alternatively, we could use something like the linguist package, or even use the GitHub API, e.g.:
```
GET https://api.github.com/repos/research-software-directory/research-software-directory/languages
```
